# 04 · IDUN raw → LSL alignment

Generate `idun_repair_root/idun_repair_summary.csv`, then align native IDUN EEG with cap EEG in matching XDFs under `processing_data_root`. No earlier synchronization step is required.

In [1]:
import importlib
import sys
from pathlib import Path

from IPython.display import display

for PROJECT_ROOT in (Path.cwd().resolve(), *Path.cwd().resolve().parents):
    if (PROJECT_ROOT / 'helpers').is_dir():
        sys.path.insert(0, str(PROJECT_ROOT))
        break
else:
    raise FileNotFoundError('Could not locate the ImBrAid/helpers folder')

from helpers.idun import raw_lsl_repair as repair
from helpers.project_config import load_project_config
from helpers.sync_quality import idun_lsl_alignment as alignment
importlib.reload(repair)
importlib.reload(alignment)

CONFIG = load_project_config(PROJECT_ROOT / 'config.json')
DATA_ROOT = CONFIG.path('paths', 'processing_data_root')
REPAIR_ROOT = CONFIG.path('paths', 'idun_repair_root')
ALIGNMENT_CSV = CONFIG.path('files', 'idun_lsl_alignment_csv')
OVERWRITE = True
PARTICIPANTS = None
VISITS = None
CHUNK_SAMPLES = 20
REPAIR_SEARCH_RADIUS_S = 30.0
CAP_STREAM_NAME = CONFIG.value('modalities', 'cap_eeg_stream_name')
BASE_HZ = 50.0
FEATURE_HZ = 10.0
WINDOW_S = 300.0
STEP_S = 150.0
COARSE_SEARCH_RADIUS_S = 30.0
LOCAL_SEARCH_RADIUS_S = 2.0
MINIMUM_PEAK_CORRELATION = 0.35
MINIMUM_PEAK_MARGIN = 0.02
REVIEW_DRIFT_PPM = 2000.0
MAXIMUM_DRIFT_PPM = 10000.0

In [2]:
repair_jobs = repair.discover_idun_jobs(
    DATA_ROOT, project=CONFIG.project, participants=PARTICIPANTS, visits=VISITS,
)

display(repair_jobs[['pid', 'visit', 'discovery_status']])

       pid visit discovery_status
0   A7G5SM    VX      missing_raw
1   ABVLGQ    VX            ready
2   B9NYQ8    VX      missing_raw
3   CRVWF9    VX            ready
4   CRYSEP    VX            ready
5   CU6DM4    VX            ready
6   DUJL2L    VX            ready
7   E4MKXT    VX            ready
8   EASFXM    VX            ready
9   FEDZAG    VX            ready
10  FGJK2B    VX      missing_raw
11  FLZWD8    VX            ready
12  G93LYM    VX            ready
13  GLRNU9    VX            ready
14  HH5RBX    VX            ready
15  HKJPM3    VX      missing_raw
16  HNWSPB    VX      missing_raw
17  JVC62S    VX      missing_raw
18  LGJEFY    VX            ready
19  LKK2WT    VX            ready
20  MUHKQF    VX            ready
21  N37VFK    VX      missing_raw
22  N7C4A6    VX      missing_raw
23  NJN65T    VX      missing_raw
24  PJ52F4    VX            ready
25  Q5ZPCB    VX      missing_raw
26  R595WP    VX            ready
27  R8YB77    VX      missing_raw
28  RYE8J9    VX            ready
29  RZKLE8    VX            ready
30  S99GF9    VX      missing_raw
31  SHUPW7    VX            ready
32  SPKHNL    VX            ready
33  TXRE5B    VX            ready
34  U83GH3    VX            ready
35  UY6WA8    VX            ready
36  V3SLBM    VX      missing_raw
37  VUT5TP    VX            ready
38  W3MTYZ    VX      missing_raw
39  XJF6R9    VX      missing_raw
40  YHYKDQ    VX            ready
41  Z8HDMS    VX      missing_raw
42  ZQTXLD    VX            ready

In [3]:
repair_summary = repair.run_idun_repairs(
    repair_jobs, REPAIR_ROOT, chunk_samples=CHUNK_SAMPLES,
    search_radius_s=REPAIR_SEARCH_RADIUS_S,
)

display(repair_summary[[
    'pid', 'visit', 'repair_status', 'usable_relative_time',
    'quality_grade', 'review_required', 'matched_chunk_ratio', 'warnings',
]])

,pid,visit,repair_status,usable_relative_time,quality_grade,review_required,matched_chunk_ratio,warnings
0,A7G5SM,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
1,ABVLGQ,VX,repaired,True,A,False,1.0,18 chunk transitions were not in raw acquisiti...
2,B9NYQ8,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
3,CRVWF9,VX,repaired,True,A,False,1.0,272 chunk transitions were not in raw acquisit...
4,CRYSEP,VX,repaired,True,A,False,1.0,120 chunk transitions were not in raw acquisit...
5,CU6DM4,VX,repaired,True,A,False,1.0,364 chunk transitions were not in raw acquisit...
6,DUJL2L,VX,repaired,True,A,False,1.0,193 chunk transitions were not in raw acquisit...
7,E4MKXT,VX,repaired,True,A,False,1.0,424 chunk transitions were not in raw acquisit...
8,EASFXM,VX,repaired,True,A,False,1.0,295 chunk transitions were not in raw acquisit...
9,FEDZAG,VX,repaired,True,A,False,1.0,295 chunk transitions were not in raw acquisit...
10,FGJK2B,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
11,FLZWD8,VX,repaired,True,A,False,1.0,357 chunk transitions were not in raw acquisit...
12,G93LYM,VX,repaired,True,A,False,1.0,315 chunk transitions were not in raw acquisit...
13,GLRNU9,VX,repaired,True,A,False,1.0,263 chunk transitions were not in raw acquisit...
14,HH5RBX,VX,repaired,True,A,False,1.0,296 chunk transitions were not in raw acquisit...
15,HKJPM3,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
16,HNWSPB,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
17,JVC62S,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
18,LGJEFY,VX,repaired,True,A,False,1.0,322 chunk transitions were not in raw acquisit...
19,LKK2WT,VX,repaired,True,A,False,1.0,375 chunk transitions were not in raw acquisit...
20,MUHKQF,VX,repaired,True,A,False,1.0,352 chunk transitions were not in raw acquisit...
21,N37VFK,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
22,N7C4A6,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
23,NJN65T,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
24,PJ52F4,VX,repaired,True,A,False,1.0,33 chunk transitions were not in raw acquisiti...
25,Q5ZPCB,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
26,R595WP,VX,repaired,True,A,False,1.0,715 chunk transitions were not in raw acquisit...
27,R8YB77,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
28,RYE8J9,VX,repaired,True,A,False,1.0,539 chunk transitions were not in raw acquisit...
29,RZKLE8,VX,repaired,True,A,False,1.0,318 chunk transitions were not in raw acquisit...
30,S99GF9,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
31,SHUPW7,VX,failed,False,D,True,NaN,ValueError: IDUN raw EEG CSV is empty: E:\test...
32,SPKHNL,VX,repaired,True,A,False,1.0,321 chunk transitions were not in raw acquisit...
33,TXRE5B,VX,repaired,True,A,False,1.0,313 chunk transitions were not in raw acquisit...
34,U83GH3,VX,repaired_with_review,True,B,True,1.0,263 chunk transitions were not in raw acquisit...
35,UY6WA8,VX,repaired,True,A,False,1.0,296 chunk transitions were not in raw acquisit...
36,V3SLBM,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
37,VUT5TP,VX,repaired,True,A,False,1.0,405 chunk transitions were not in raw acquisit...
38,W3MTYZ,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
39,XJF6R9,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
40,YHYKDQ,VX,repaired,True,A,False,1.0,342 chunk transitions were not in raw acquisit...
41,Z8HDMS,VX,unavailable,False,D,True,NaN,Discovery status: missing_raw
42,ZQTXLD,VX,repaired,True,A,False,1.0,401 chunk transitions were not in raw acquisit...

In [4]:
jobs = alignment.discover_cap_eeg_sync_jobs(
    REPAIR_ROOT, participants=PARTICIPANTS, visits=VISITS,
)
display(jobs[['pid', 'visit', 'discovery_status']])

       pid visit      discovery_status
0   A7G5SM    VX  idun_repair_unusable
1   ABVLGQ    VX                 ready
2   B9NYQ8    VX  idun_repair_unusable
3   CRVWF9    VX                 ready
4   CRYSEP    VX                 ready
5   CU6DM4    VX                 ready
6   DUJL2L    VX                 ready
7   E4MKXT    VX                 ready
8   EASFXM    VX                 ready
9   FEDZAG    VX                 ready
10  FGJK2B    VX  idun_repair_unusable
11  FLZWD8    VX                 ready
12  G93LYM    VX                 ready
13  GLRNU9    VX                 ready
14  HH5RBX    VX                 ready
15  HKJPM3    VX  idun_repair_unusable
16  HNWSPB    VX  idun_repair_unusable
17  JVC62S    VX  idun_repair_unusable
18  LGJEFY    VX                 ready
19  LKK2WT    VX                 ready
20  MUHKQF    VX                 ready
21  N37VFK    VX  idun_repair_unusable
22  N7C4A6    VX  idun_repair_unusable
23  NJN65T    VX  idun_repair_unusable
24  PJ52F4    VX                 ready
25  Q5ZPCB    VX  idun_repair_unusable
26  R595WP    VX                 ready
27  R8YB77    VX  idun_repair_unusable
28  RYE8J9    VX                 ready
29  RZKLE8    VX                 ready
30  S99GF9    VX  idun_repair_unusable
31  SHUPW7    VX  idun_repair_unusable
32  SPKHNL    VX                 ready
33  TXRE5B    VX                 ready
34  U83GH3    VX                 ready
35  UY6WA8    VX                 ready
36  V3SLBM    VX  idun_repair_unusable
37  VUT5TP    VX                 ready
38  W3MTYZ    VX  idun_repair_unusable
39  XJF6R9    VX  idun_repair_unusable
40  YHYKDQ    VX                 ready
41  Z8HDMS    VX  idun_repair_unusable
42  ZQTXLD    VX                 ready

In [5]:
mappings = alignment.build_idun_cap_alignments(
    jobs, cap_stream_name=CAP_STREAM_NAME, base_hz=BASE_HZ,
    feature_hz=FEATURE_HZ, window_s=WINDOW_S, step_s=STEP_S,
    coarse_search_radius_s=COARSE_SEARCH_RADIUS_S,
    local_search_radius_s=LOCAL_SEARCH_RADIUS_S,
    minimum_peak_correlation=MINIMUM_PEAK_CORRELATION,
    minimum_peak_margin=MINIMUM_PEAK_MARGIN,
    review_drift_ppm=REVIEW_DRIFT_PPM,
    maximum_drift_ppm=MAXIMUM_DRIFT_PPM,
)
if OVERWRITE:
    alignment.save_idun_cap_alignment_results(
        mappings, alignment_csv=ALIGNMENT_CSV,
    )
display(mappings[[
    'pid', 'visit', 'mapping_status', 'usable', 'quality_grade',
    'review_required', 'selected_cap_feature', 'drift_ppm',
    'n_good_windows', 'fit_residual_p95_s',
    'mapping_reason', 'warnings',
]])

,pid,visit,mapping_status,usable,quality_grade,review_required,selected_cap_feature,drift_ppm,n_good_windows,fit_residual_p95_s,mapping_reason,warnings
0,A7G5SM,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
1,ABVLGQ,VX,affine,True,A,False,T7-T8,-569.032235,17.0,0.018729,Supported affine mapping from IDUN and cap EEG...,
2,B9NYQ8,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
3,CRVWF9,VX,affine,True,A,False,T7-T8,-1107.618332,16.0,0.056666,Supported affine mapping from IDUN and cap EEG...,
4,CRYSEP,VX,affine,True,A,False,T7-T8,-345.416163,6.0,0.028706,Supported affine mapping from IDUN and cap EEG...,
5,CU6DM4,VX,affine,True,A,False,T7-T8,-428.468097,17.0,0.035443,Supported affine mapping from IDUN and cap EEG...,
6,DUJL2L,VX,affine_review,True,B,True,T8-M1,-762.212185,17.0,0.071696,Usable affine mapping with review-level qualit...,median peak correlation was 0.593
7,E4MKXT,VX,affine,True,A,False,T7-T8,-836.290677,16.0,0.047424,Supported affine mapping from IDUN and cap EEG...,
8,EASFXM,VX,affine,True,A,False,T7-T8,-1006.836460,17.0,0.054746,Supported affine mapping from IDUN and cap EEG...,
9,FEDZAG,VX,affine,True,A,False,T7-T8,-857.608382,16.0,0.052702,Supported affine mapping from IDUN and cap EEG...,
10,FGJK2B,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
11,FLZWD8,VX,affine,True,A,False,M1-M2,-988.526756,16.0,0.047517,Supported affine mapping from IDUN and cap EEG...,
12,G93LYM,VX,affine,True,A,False,T7-T8,-473.862077,16.0,0.054794,Supported affine mapping from IDUN and cap EEG...,
13,GLRNU9,VX,affine,True,A,False,T7-T8,-571.146029,13.0,0.020648,Supported affine mapping from IDUN and cap EEG...,
14,HH5RBX,VX,affine,True,A,False,T7-T8,-772.464436,16.0,0.075334,Supported affine mapping from IDUN and cap EEG...,
15,HKJPM3,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
16,HNWSPB,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
17,JVC62S,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
18,LGJEFY,VX,affine,True,A,False,T7-T8,-602.089339,17.0,0.052532,Supported affine mapping from IDUN and cap EEG...,
19,LKK2WT,VX,affine,True,A,False,T7-T8,-342.287652,17.0,0.047188,Supported affine mapping from IDUN and cap EEG...,
20,MUHKQF,VX,affine,True,A,False,T7-T8,-474.297677,17.0,0.033162,Supported affine mapping from IDUN and cap EEG...,
21,N37VFK,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
22,N7C4A6,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
23,NJN65T,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
24,PJ52F4,VX,affine,True,A,False,T7-T8,-388.172763,17.0,0.038676,Supported affine mapping from IDUN and cap EEG...,
25,Q5ZPCB,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
26,R595WP,VX,affine,True,A,False,T7-T8,-1062.483357,17.0,0.163489,Supported affine mapping from IDUN and cap EEG...,
27,R8YB77,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
28,RYE8J9,VX,affine,True,A,False,T7-T8,-572.603716,16.0,0.022526,Supported affine mapping from IDUN and cap EEG...,
29,RZKLE8,VX,affine_review,True,B,True,T7,-433.271190,17.0,0.107778,Usable affine mapping with review-level qualit...,median peak correlation was 0.564
30,S99GF9,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
31,SHUPW7,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
32,SPKHNL,VX,affine,True,A,False,T7-T8,-486.494040,14.0,0.032802,Supported affine mapping from IDUN and cap EEG...,
33,TXRE5B,VX,affine,True,A,False,T8-M1,-584.263662,16.0,0.068759,Supported affine mapping from IDUN and cap EEG...,
34,U83GH3,VX,affine,True,A,False,M1-M2,-632.930471,16.0,0.062804,Supported affine mapping from IDUN and cap EEG...,
35,UY6WA8,VX,affine,True,A,False,T7-T8,-886.539893,16.0,0.076850,Supported affine mapping from IDUN and cap EEG...,
36,V3SLBM,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
37,VUT5TP,VX,affine,True,A,False,T7-T8,-759.894154,17.0,0.020188,Supported affine mapping from IDUN and cap EEG...,
38,W3MTYZ,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
39,XJF6R9,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
40,YHYKDQ,VX,affine,True,A,False,T7-T8,-682.101701,17.0,0.029262,Supported affine mapping from IDUN and cap EEG...,
41,Z8HDMS,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,Discovery status: idun_repair_unusable,Discovery status: idun_repair_unusable
42,ZQTXLD,VX,affine,True,A,False,T7-T8,-743.798247,17.0,0.082190,Supported affine mapping from IDUN and cap EEG...,