# 01 · ET raw → LSL alignment

Build the common ET-raw/LSL affine clock mapping and its QC tables. This is the shared time-axis prerequisite for all three publication exports.

In [1]:
import importlib
import sys
from pathlib import Path

import pandas as pd
from IPython.display import display

for PROJECT_ROOT in (Path.cwd().resolve(), *Path.cwd().resolve().parents):
    if (PROJECT_ROOT / 'helpers').is_dir():
        sys.path.insert(0, str(PROJECT_ROOT))
        break
else:
    raise FileNotFoundError('Could not locate the BIGPROJECT/helpers folder')

from helpers.project_config import load_project_config
from helpers.sync_quality import et_lsl_alignment as alignment
importlib.reload(alignment)

CONFIG = load_project_config(PROJECT_ROOT / 'ImBrAid' / 'config.json')
PROJECT_NAME = CONFIG.project
DATA_ROOT = CONFIG.path('paths', 'processing_data_root')
ALIGNMENT_CSV = CONFIG.path('files', 'et_lsl_alignment_csv')
WINDOWS_CSV = CONFIG.path('files', 'et_lsl_windows_csv')
ISSUES_CSV = CONFIG.path('files', 'et_lsl_issues_csv')
OVERWRITE = True
PARTICIPANTS = None
VISITS = None
LEGACY_MAPPING_CSV = None
WINDOW_S = 60.0
STEP_S = 30.0
LOCAL_RESIDUAL_SEARCH_RADIUS_S = 10.0
MIN_GOOD_WINDOWS = 3
REVIEW_DRIFT_PPM = 2000.0
MAX_DRIFT_PPM = 10000.0

In [2]:
jobs = alignment.discover_et_lsl_jobs(
    DATA_ROOT, project=PROJECT_NAME, participants=PARTICIPANTS, visits=VISITS,
)
display(jobs[['pid', 'visit', 'discovery_status', 'et_candidate_count', 'xdf_candidate_count']])

       pid visit  discovery_status  et_candidate_count  xdf_candidate_count
0   A7G5SM    VX             ready                   1                    1
1   ABVLGQ    VX             ready                   1                    1
2   B9NYQ8    VX             ready                   1                    1
3   CRVWF9    VX             ready                   1                    1
4   CRYSEP    VX             ready                   1                    1
5   CU6DM4    VX             ready                   1                    1
6   DUJL2L    VX             ready                   1                    1
7   E4MKXT    VX             ready                   1                    1
8   EASFXM    VX             ready                   1                    1
9   FEDZAG    VX             ready                   1                    1
10  FGJK2B    VX             ready                   1                    1
11  FLZWD8    VX             ready                   1                    1
12  G93LYM    VX             ready                   1                    1
13  GLRNU9    VX             ready                   1                    1
14  HH5RBX    VX             ready                   1                    1
15  HKJPM3    VX  ambiguous_et_raw                   2                    1
16  HNWSPB    VX             ready                   1                    1
17  JVC62S    VX             ready                   1                    1
18  LGJEFY    VX             ready                   1                    1
19  LKK2WT    VX             ready                   1                    1
20  MUHKQF    VX             ready                   1                    1
21  N37VFK    VX             ready                   1                    1
22  N7C4A6    VX             ready                   1                    1
23  NJN65T    VX             ready                   1                    1
24  PJ52F4    VX             ready                   1                    1
25  Q5ZPCB    VX             ready                   1                    1
26  R595WP    VX             ready                   1                    1
27  R8YB77    VX             ready                   1                    1
28  RYE8J9    VX             ready                   1                    1
29  RZKLE8    VX             ready                   1                    1
30  S99GF9    VX             ready                   1                    1
31  SHUPW7    VX             ready                   1                    1
32  SPKHNL    VX             ready                   1                    1
33  TXRE5B    VX             ready                   1                    1
34  U83GH3    VX             ready                   1                    1
35  UY6WA8    VX             ready                   1                    1
36  V3SLBM    VX             ready                   1                    1
37  VUT5TP    VX             ready                   1                    1
38  W3MTYZ    VX             ready                   1                    1
39  XJF6R9    VX             ready                   1                    1
40  YHYKDQ    VX             ready                   1                    1
41  Z8HDMS    VX             ready                   1                    1
42  ZQTXLD    VX             ready                   1                    1

In [3]:
legacy = (
    pd.read_csv(LEGACY_MAPPING_CSV, dtype={'pid': str, 'visit': str})
    if LEGACY_MAPPING_CSV is not None and Path(LEGACY_MAPPING_CSV).is_file()
    else None
)
alignments, windows, issues = alignment.build_et_lsl_alignments(
    jobs, legacy_results=legacy, window_s=WINDOW_S, step_s=STEP_S,
    local_residual_search_radius_s=LOCAL_RESIDUAL_SEARCH_RADIUS_S,
    min_good_windows=MIN_GOOD_WINDOWS, review_drift_ppm=REVIEW_DRIFT_PPM,
    max_drift_ppm=MAX_DRIFT_PPM,
)
if OVERWRITE:
    alignment.save_et_lsl_alignment_results(
        alignments, windows, issues, alignment_csv=ALIGNMENT_CSV,
        windows_csv=WINDOWS_CSV, issues_csv=ISSUES_CSV,
    )
display(alignments[[
    'pid', 'visit', 'mapping_status', 'usable', 'quality_grade',
    'review_required', 'drift_ppm', 'n_good_windows',
    'fit_residual_p95_s', 'mapping_reason', 'warnings',
]])
display(issues)

Stream 1: Calculated effective sampling rate 41.0292 Hz is different from specified rate 50.0000 Hz.
Stream 11: Calculated effective sampling rate 41.0292 Hz is different from specified rate 50.0000 Hz.
Stream 7: Calculated effective sampling rate 41.0292 Hz is different from specified rate 50.0000 Hz.
Stream 2: Calculated effective sampling rate 0.1998 Hz is different from specified rate 10.0000 Hz.
Stream 9: Calculated effective sampling rate 41.0292 Hz is different from specified rate 50.0000 Hz.
Stream 8: Calculated effective sampling rate 41.0292 Hz is different from specified rate 50.0000 Hz.
Stream 3: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 8: Calculated effective sampling rate 0.0000 Hz is different from specified rate 250.0000 Hz.
Stream 9: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 3: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 11: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 13: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 10: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 13: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 11: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 9: Calculated effective sampling rate 0.2005 Hz is different from specified rate 10.0000 Hz.
Stream 8: Calculated effective sampling rate 42.8578 Hz is different from specified rate 50.0000 Hz.
Stream 11: Calculated effective sampling rate 42.8578 Hz is different from specified rate 50.0000 Hz.
Stream 4: Calculated effective sampling rate 42.8578 Hz is different from specified rate 50.0000 Hz.
Stream 3: Calculated effective sampling rate 0.1998 Hz is different from specified rate 10.0000 Hz.
Stream 6: Calculated effective sampling rate 42.8578 Hz is different from specified rate 50.0000 Hz.
Stream 2: Calculated effective sampling rate 42.8578 Hz is different from specified rate 50.0000 Hz.
Stream 5: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 6: Calculated effective sampling rate 0.2009 Hz is different from specified rate 10.0000 Hz.
Stream 2: Calculated effective sampling rate 0.1999 Hz is different from specified rate 10.0000 Hz.
Stream 11: Calculated effective sampling rate 0.1998 Hz is different from specified rate 10.0000 Hz.
Stream 8: Calculated effective sampling rate 41.3712 Hz is different from specified rate 50.0000 Hz.
Stream 2: Calculated effective sampling rate 41.3712 Hz is different from specified rate 50.0000 Hz.
Stream 6: Calculated effective sampling rate 41.3712 Hz is different from specified rate 50.0000 Hz.
Stream 12: Calculated effective sampling rate 0.2003 Hz is different from specified rate 10.0000 Hz.
Stream 3: Calculated effective sampling rate 41.3712 Hz is different from specified rate 50.0000 Hz.
Stream 4: Calculated effective sampling rate 41.3712 Hz is different from specified rate 50.0000 Hz.
Stream 3: Calculated effective sampling rate 0.1999 Hz is different from specified rate 10.0000 Hz.
Stream 11: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 1: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 7: Calculated effective sampling rate 0.2002 Hz is different from specified rate 10.0000 Hz.
Stream 10: Calculated effective sampling rate 39.2552 Hz is different from specified rate 50.0000 Hz.
Stream 8: Calculated effective sampling rate 0.1999 Hz is different from specified rate 10.0000 Hz.
Stream 6: Calculated effective sampling rate 39.2552 Hz is different from specified rate 50.0000 Hz.
Stream 7: Calculated effective sampling rate 39.2552 Hz is different from specified rate 50.0000 Hz.
Stream 9: Calculated effective sampling rate 39.2552 Hz is different from specified rate 50.0000 Hz.
Stream 12: Calculated effective sampling rate 39.2552 Hz is different from specified rate 50.0000 Hz.
Stream 7: Calculated effective sampling rate 41.5941 Hz is different from specified rate 50.0000 Hz.
Stream 5: Calculated effective sampling rate 41.5941 Hz is different from specified rate 50.0000 Hz.
Stream 6: Calculated effective sampling rate 41.5941 Hz is different from specified rate 50.0000 Hz.
Stream 10: Calculated effective sampling rate 41.5941 Hz is different from specified rate 50.0000 Hz.
Stream 3: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 9: Calculated effective sampling rate 41.5941 Hz is different from specified rate 50.0000 Hz.
Stream 6: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 7: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 13: Calculated effective sampling rate 0.1995 Hz is different from specified rate 10.0000 Hz.
Stream 1: Calculated effective sampling rate 0.1996 Hz is different from specified rate 10.0000 Hz.

Warning: multiple streams found for Gyroscope, using the one with longest data
Warning: multiple streams found for Gaze3d, using the one with longest data
Warning: multiple streams found for Gaze2d, using the one with longest data
Warning: multiple streams found for GazeDirection, using the one with longest data
Warning: multiple streams found for GazeOrigin, using the one with longest data
Warning: multiple streams found for Magnetometer, using the one with longest data
Warning: multiple streams found for Pupil, using the one with longest data
Warning: multiple streams found for Accelerometer, using the one with longest data

Stream 3: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 1: Calculated effective sampling rate 43.5574 Hz is different from specified rate 50.0000 Hz.
Stream 7: Calculated effective sampling rate 0.1999 Hz is different from specified rate 10.0000 Hz.
Stream 6: Calculated effective sampling rate 43.5574 Hz is different from specified rate 50.0000 Hz.
Stream 11: Calculated effective sampling rate 43.5574 Hz is different from specified rate 50.0000 Hz.
Stream 8: Calculated effective sampling rate 43.5574 Hz is different from specified rate 50.0000 Hz.
Stream 9: Calculated effective sampling rate 43.5574 Hz is different from specified rate 50.0000 Hz.
Stream 10: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 8: Calculated effective sampling rate 0.1999 Hz is different from specified rate 10.0000 Hz.
Stream 8: Calculated effective sampling rate 0.2224 Hz is different from specified rate 10.0000 Hz.
Stream 2: Calculated effective sampling rate 129.1096 Hz is different from specified rate 117.0000 Hz.
Stream 6: Calculated effective sampling rate 129.1096 Hz is different from specified rate 117.0000 Hz.
Stream 2: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 6: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 5: Calculated effective sampling rate 0.1998 Hz is different from specified rate 10.0000 Hz.
Stream 6: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 12: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 8: Calculated effective sampling rate 0.2005 Hz is different from specified rate 10.0000 Hz.
Stream 13: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 3: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 5: Calculated effective sampling rate 0.2008 Hz is different from specified rate 10.0000 Hz.
Stream 6: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 5: Calculated effective sampling rate 0.0000 Hz is different from specified rate 250.0000 Hz.
Stream 6: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.
Stream 6: Calculated effective sampling rate 0.1997 Hz is different from specified rate 10.0000 Hz.

,pid,visit,mapping_status,usable,quality_grade,review_required,drift_ppm,n_good_windows,fit_residual_p95_s,mapping_reason,warnings
0,A7G5SM,VX,content_affine,True,B,False,-7.209940,69.0,0.019176,local content windows,residual p95 4.046 s exceeds limit | possible ...
1,ABVLGQ,VX,content_affine,True,A,False,9.429200,89.0,0.001292,local content windows,
2,B9NYQ8,VX,content_affine,True,A,False,9.171459,89.0,0.001561,local content windows,
3,CRVWF9,VX,content_affine,True,A,False,8.997442,88.0,0.001241,local content windows,
4,CRYSEP,VX,content_affine,True,A,False,10.443689,89.0,0.000934,local content windows,
5,CU6DM4,VX,content_affine,True,A,False,9.799556,93.0,0.001256,local content windows,
6,DUJL2L,VX,content_affine,True,A,False,10.948969,91.0,0.001274,local content windows,
7,E4MKXT,VX,content_affine,True,A,False,7.508684,89.0,0.001194,local content windows,
8,EASFXM,VX,content_affine,True,A,False,8.914502,89.0,0.001421,local content windows,
9,FEDZAG,VX,content_affine,True,A,False,975.412432,88.0,0.108333,local content windows,
10,FGJK2B,VX,content_affine,True,B,False,-5.563397,83.0,0.018489,local content windows,residual p95 4.727 s exceeds limit | possible ...
11,FLZWD8,VX,content_affine,True,A,False,8.097160,88.0,0.001343,local content windows,
12,G93LYM,VX,unavailable,False,D,True,NaN,NaN,NaN,residual p95 2.610 s exceeds limit; possible c...,residual p95 2.610 s exceeds limit | possible ...
13,GLRNU9,VX,content_affine,True,A,False,7.936614,75.0,0.002594,local content windows,
14,HH5RBX,VX,content_affine,True,A,False,322.542726,86.0,0.002605,local content windows,
15,HKJPM3,VX,unavailable,False,D,True,NaN,NaN,NaN,ambiguous_et_raw,
16,HNWSPB,VX,content_affine,True,B,False,12.536421,40.0,0.002148,local content windows,residual p95 1.048 s exceeds limit | possible ...
17,JVC62S,VX,unavailable,False,D,True,NaN,NaN,NaN,only 1 good windows / 1 fit inliers,only 1 good windows / 1 fit inliers | no fitte...
18,LGJEFY,VX,content_affine,True,A,False,10.321015,89.0,0.001225,local content windows,
19,LKK2WT,VX,content_affine,True,B,False,6.456142,90.0,0.019133,local content windows,residual p95 0.594 s exceeds limit | residual ...
20,MUHKQF,VX,content_affine,True,A,False,21.921235,53.0,0.001349,local content windows,
21,N37VFK,VX,unavailable,False,D,True,NaN,NaN,NaN,only 1 good windows / 1 fit inliers,only 1 good windows / 1 fit inliers | no fitte...
22,N7C4A6,VX,content_affine,True,B,False,-3.123398,90.0,0.020915,local content windows,residual p95 3.307 s exceeds limit | possible ...
23,NJN65T,VX,content_affine,True,B,False,7.709380,90.0,0.016627,local content windows,possible clock jump 4.308 s | residual p95 4.3...
24,PJ52F4,VX,content_affine,True,A,False,9.906075,89.0,0.001206,local content windows,
25,Q5ZPCB,VX,content_affine,True,A,False,10.752571,89.0,0.001980,local content windows,
26,R595WP,VX,content_affine,True,A,False,9.789256,89.0,0.001696,local content windows,
27,R8YB77,VX,content_affine,True,B,False,10.076625,65.0,0.034341,local content windows,residual p95 4.246 s exceeds limit | possible ...
28,RYE8J9,VX,content_affine,True,A,False,8.578479,89.0,0.001214,local content windows,
29,RZKLE8,VX,content_affine,True,A,False,166.599229,63.0,0.001569,local content windows,
30,S99GF9,VX,content_affine,True,B,False,7.029392,85.0,0.001847,local content windows,residual p95 3.591 s exceeds limit | possible ...
31,SHUPW7,VX,content_affine,True,A,False,350.272156,92.0,0.002214,local content windows,
32,SPKHNL,VX,content_affine,True,A,False,7.956108,89.0,0.001633,local content windows,
33,TXRE5B,VX,content_affine,True,A,False,8.938502,88.0,0.011402,local content windows,
34,U83GH3,VX,content_affine,True,A,False,7.835696,89.0,0.001300,local content windows,
35,UY6WA8,VX,content_affine,True,A,False,7.162755,89.0,0.001481,local content windows,
36,V3SLBM,VX,unavailable,False,D,True,NaN,NaN,NaN,no fitted mapping,no fitted mapping
37,VUT5TP,VX,content_affine,True,A,False,9.135688,89.0,0.001731,local content windows,
38,W3MTYZ,VX,unavailable,False,D,True,NaN,NaN,NaN,residual p95 7.453 s exceeds limit; possible c...,residual p95 7.453 s exceeds limit | possible ...
39,XJF6R9,VX,content_affine,True,B,False,12.576239,23.0,0.009079,local content windows,possible clock jump 2.913 s | residual p95 2.5...
40,YHYKDQ,VX,content_affine,True,A,False,8.458018,90.0,0.001700,local content windows,
41,Z8HDMS,VX,content_affine,True,A,False,8.849516,89.0,0.019304,local content windows,
42,ZQTXLD,VX,content_affine,True,A,False,8.272475,90.0,0.001304,local content windows,

,project,pid,visit,severity,code,message
0,ImBrAid,A7G5SM,VX,warning,fit_qc,residual p95 4.046 s exceeds limit
1,ImBrAid,A7G5SM,VX,warning,fit_qc,possible clock jump 4.674 s
2,ImBrAid,A7G5SM,VX,warning,fit_qc,residual p95 3.962 s exceeds limit
3,ImBrAid,A7G5SM,VX,warning,fit_qc,possible clock jump 2.417 s
4,ImBrAid,FGJK2B,VX,warning,fit_qc,residual p95 4.727 s exceeds limit
5,ImBrAid,FGJK2B,VX,warning,fit_qc,possible clock jump 9.374 s
6,ImBrAid,FGJK2B,VX,warning,fit_qc,residual p95 8.245 s exceeds limit
7,ImBrAid,FGJK2B,VX,warning,fit_qc,possible clock jump 13.752 s
8,ImBrAid,G93LYM,VX,warning,fit_qc,residual p95 2.610 s exceeds limit
9,ImBrAid,G93LYM,VX,warning,fit_qc,possible clock jump 9.107 s
10,ImBrAid,G93LYM,VX,warning,fit_qc,no fitted mapping
11,ImBrAid,HKJPM3,VX,error,discovery_not_ready,ambiguous_et_raw
12,ImBrAid,HNWSPB,VX,warning,fit_qc,residual p95 1.048 s exceeds limit
13,ImBrAid,HNWSPB,VX,warning,fit_qc,possible clock jump 1.587 s
14,ImBrAid,HNWSPB,VX,warning,fit_qc,residual p95 1.126 s exceeds limit
15,ImBrAid,HNWSPB,VX,warning,fit_qc,possible clock jump 1.566 s
16,ImBrAid,JVC62S,VX,warning,fit_qc,only 1 good windows / 1 fit inliers
17,ImBrAid,JVC62S,VX,warning,fit_qc,no fitted mapping
18,ImBrAid,LKK2WT,VX,warning,fit_qc,residual p95 0.594 s exceeds limit
19,ImBrAid,LKK2WT,VX,warning,fit_qc,residual p95 0.593 s exceeds limit
20,ImBrAid,N37VFK,VX,warning,fit_qc,only 1 good windows / 1 fit inliers
21,ImBrAid,N37VFK,VX,warning,fit_qc,no fitted mapping
22,ImBrAid,N7C4A6,VX,warning,fit_qc,residual p95 3.307 s exceeds limit
23,ImBrAid,N7C4A6,VX,warning,fit_qc,possible clock jump 6.954 s
24,ImBrAid,N7C4A6,VX,warning,fit_qc,residual p95 6.657 s exceeds limit
25,ImBrAid,N7C4A6,VX,warning,fit_qc,possible clock jump 1.750 s
26,ImBrAid,NJN65T,VX,warning,fit_qc,possible clock jump 4.308 s
27,ImBrAid,NJN65T,VX,warning,fit_qc,residual p95 4.322 s exceeds limit
28,ImBrAid,NJN65T,VX,warning,fit_qc,possible clock jump 2.225 s
29,ImBrAid,R8YB77,VX,warning,fit_qc,residual p95 4.246 s exceeds limit
30,ImBrAid,R8YB77,VX,warning,fit_qc,possible clock jump 3.350 s
31,ImBrAid,S99GF9,VX,warning,fit_qc,residual p95 3.591 s exceeds limit
32,ImBrAid,S99GF9,VX,warning,fit_qc,possible clock jump 6.398 s
33,ImBrAid,S99GF9,VX,warning,fit_qc,residual p95 7.718 s exceeds limit
34,ImBrAid,S99GF9,VX,warning,fit_qc,possible clock jump 14.887 s
35,ImBrAid,V3SLBM,VX,warning,fit_qc,no fitted mapping
36,ImBrAid,W3MTYZ,VX,warning,fit_qc,residual p95 7.453 s exceeds limit
37,ImBrAid,W3MTYZ,VX,warning,fit_qc,possible clock jump 13.416 s
38,ImBrAid,W3MTYZ,VX,warning,fit_qc,only 2 good windows / 2 fit inliers
39,ImBrAid,W3MTYZ,VX,warning,fit_qc,residual p95 2.122 s exceeds limit
40,ImBrAid,W3MTYZ,VX,warning,fit_qc,possible clock jump 4.245 s
41,ImBrAid,W3MTYZ,VX,warning,fit_qc,residual p95 3.369 s exceeds limit
42,ImBrAid,W3MTYZ,VX,warning,fit_qc,possible clock jump 5.981 s
43,ImBrAid,XJF6R9,VX,warning,fit_qc,possible clock jump 2.913 s
44,ImBrAid,XJF6R9,VX,warning,fit_qc,residual p95 2.579 s exceeds limit
45,ImBrAid,XJF6R9,VX,warning,fit_qc,possible clock jump 2.944 s