# 02 · DriverVideo → ET raw alignment

Annotate the shared speedometer-panel transitions and fit Driver exact-PTS time to ET raw. This step saves mapping/QC only; step 10 composes it with step 01 and writes compact DriverVideo files.

In [1]:
import importlib
import sys
from pathlib import Path

from IPython.display import display

for PROJECT_ROOT in (Path.cwd().resolve(), *Path.cwd().resolve().parents):
    if (PROJECT_ROOT / 'helpers').is_dir():
        sys.path.insert(0, str(PROJECT_ROOT))
        break
else:
    raise FileNotFoundError('Could not locate the BIGPROJECT/helpers folder')

from helpers.project_config import load_project_config
from helpers.sync_quality import driver_et_alignment as alignment
from helpers.sync_quality import panel_annotation as panel
importlib.reload(panel)
importlib.reload(alignment)

CONFIG = load_project_config(PROJECT_ROOT / 'ImBrAid' / 'config.json')
PROJECT_NAME = CONFIG.project
DATA_ROOT = CONFIG.path('paths', 'processing_data_root')
DRIVER_VIDEO_SUBFOLDER = CONFIG.value('modalities', 'driver_video_source_subfolder')
ET_SUBFOLDER = CONFIG.value('modalities', 'eyeball_source_subfolder')
ANNOTATION_CSV = CONFIG.path('files', 'panel_annotations_csv')
ALIGNMENT_CSV = CONFIG.path('files', 'driver_et_alignment_csv')
ISSUES_CSV = CONFIG.path('files', 'driver_et_issues_csv')
OVERWRITE = True
PARTICIPANTS = None
VISITS = None
DRIFT_WARNING_PPM = 2000
DRIFT_REJECT_PPM = 10000
OFFSET_ONLY_DRIFT_BOUND_PPM = 5000
MAX_PAIR_UNCERTAINTY_S = 0.5

In [2]:
jobs = panel.discover_panel_video_pairs(
    DATA_ROOT, project=PROJECT_NAME, participants=PARTICIPANTS, visits=VISITS,
    driver_subfolder=DRIVER_VIDEO_SUBFOLDER, et_subfolder=ET_SUBFOLDER,
)
display(jobs[[
    'pid', 'visit', 'driver_path', 'et_scene_path', 'discovery_status',
]])

Discovered 43 visit(s): 42 ready for paired annotation.
Missing or ambiguous videos remain in the discovery table for review.

,pid,visit,driver_path,et_scene_path,discovery_status
0,A7G5SM,VX,E:\test\time_shifted\A7G5SM\Driver Video\A7G5S...,E:\test\time_shifted\A7G5SM\ET\A7G5SM_VX_et_ra...,ready
1,ABVLGQ,VX,E:\test\time_shifted\ABVLGQ\Driver Video\ABVLG...,E:\test\time_shifted\ABVLGQ\ET\ABVLGQ_VX_et_ra...,ready
2,B9NYQ8,VX,E:\test\time_shifted\B9NYQ8\Driver Video\B9NYQ...,E:\test\time_shifted\B9NYQ8\ET\B9NYQ8_VX_et_ra...,ready
3,CRVWF9,VX,E:\test\time_shifted\CRVWF9\Driver Video\CRVWF...,E:\test\time_shifted\CRVWF9\ET\CRVWF9_VX_et_ra...,ready
4,CRYSEP,VX,E:\test\time_shifted\CRYSEP\Driver Video\CRYSE...,E:\test\time_shifted\CRYSEP\ET\CRYSEP_VX_et_ra...,ready
5,CU6DM4,VX,E:\test\time_shifted\CU6DM4\Driver Video\CU6DM...,E:\test\time_shifted\CU6DM4\ET\CU6DM4_VX_et_ra...,ready
6,DUJL2L,VX,E:\test\time_shifted\DUJL2L\Driver Video\DUJL2...,E:\test\time_shifted\DUJL2L\ET\DUJL2L_VX_et_ra...,ready
7,E4MKXT,VX,E:\test\time_shifted\E4MKXT\Driver Video\E4MKX...,E:\test\time_shifted\E4MKXT\ET\E4MKXT_VX_et_ra...,ready
8,EASFXM,VX,E:\test\time_shifted\EASFXM\Driver Video\EASFX...,E:\test\time_shifted\EASFXM\ET\EASFXM_VX_et_ra...,ready
9,FEDZAG,VX,E:\test\time_shifted\FEDZAG\Driver Video\FEDZA...,E:\test\time_shifted\FEDZAG\ET\FEDZAG_VX_et_ra...,ready
10,FGJK2B,VX,E:\test\time_shifted\FGJK2B\Driver Video\FGJK2...,E:\test\time_shifted\FGJK2B\ET\FGJK2B_VX_et_ra...,ready
11,FLZWD8,VX,E:\test\time_shifted\FLZWD8\Driver Video\FLZWD...,E:\test\time_shifted\FLZWD8\ET\FLZWD8_VX_et_ra...,ready
12,G93LYM,VX,E:\test\time_shifted\G93LYM\Driver Video\G93LY...,E:\test\time_shifted\G93LYM\ET\G93LYM_VX_et_ra...,ready
13,GLRNU9,VX,E:\test\time_shifted\GLRNU9\Driver Video\GLRNU...,E:\test\time_shifted\GLRNU9\ET\GLRNU9_VX_et_ra...,ready
14,HH5RBX,VX,E:\test\time_shifted\HH5RBX\Driver Video\HH5RB...,E:\test\time_shifted\HH5RBX\ET\HH5RBX_VX_et_ra...,ready
15,HKJPM3,VX,E:\test\time_shifted\HKJPM3\Driver Video\HKJPM...,<NA>,ambiguous_et_scene
16,HNWSPB,VX,E:\test\time_shifted\HNWSPB\Driver Video\HNWSP...,E:\test\time_shifted\HNWSPB\ET\HNWSPB_VX_et_ra...,ready
17,JVC62S,VX,E:\test\time_shifted\JVC62S\Driver Video\JVC62...,E:\test\time_shifted\JVC62S\ET\JVC62S_VX_et_ra...,ready
18,LGJEFY,VX,E:\test\time_shifted\LGJEFY\Driver Video\LGJEF...,E:\test\time_shifted\LGJEFY\ET\LGJEFY_VX_et_ra...,ready
19,LKK2WT,VX,E:\test\time_shifted\LKK2WT\Driver Video\LKK2W...,E:\test\time_shifted\LKK2WT\ET\LKK2WT_VX_et_ra...,ready
20,MUHKQF,VX,E:\test\time_shifted\MUHKQF\Driver Video\MUHKQ...,E:\test\time_shifted\MUHKQF\ET\MUHKQF_VX_et_ra...,ready
21,N37VFK,VX,E:\test\time_shifted\N37VFK\Driver Video\N37VF...,E:\test\time_shifted\N37VFK\ET\N37VFK_VX_et_ra...,ready
22,N7C4A6,VX,E:\test\time_shifted\N7C4A6\Driver Video\N7C4A...,E:\test\time_shifted\N7C4A6\ET\N7C4A6_VX_et_ra...,ready
23,NJN65T,VX,E:\test\time_shifted\NJN65T\Driver Video\NJN65...,E:\test\time_shifted\NJN65T\ET\NJN65T_VX_et_ra...,ready
24,PJ52F4,VX,E:\test\time_shifted\PJ52F4\Driver Video\PJ52F...,E:\test\time_shifted\PJ52F4\ET\PJ52F4_VX_et_ra...,ready
25,Q5ZPCB,VX,E:\test\time_shifted\Q5ZPCB\Driver Video\Q5ZPC...,E:\test\time_shifted\Q5ZPCB\ET\Q5ZPCB_VX_et_ra...,ready
26,R595WP,VX,E:\test\time_shifted\R595WP\Driver Video\R595W...,E:\test\time_shifted\R595WP\ET\R595WP_VX_et_ra...,ready
27,R8YB77,VX,E:\test\time_shifted\R8YB77\Driver Video\R8YB7...,E:\test\time_shifted\R8YB77\ET\R8YB77_VX_et_ra...,ready
28,RYE8J9,VX,E:\test\time_shifted\RYE8J9\Driver Video\RYE8J...,E:\test\time_shifted\RYE8J9\ET\RYE8J9_VX_et_ra...,ready
29,RZKLE8,VX,E:\test\time_shifted\RZKLE8\Driver Video\RZKLE...,E:\test\time_shifted\RZKLE8\ET\RZKLE8_VX_et_ra...,ready
30,S99GF9,VX,E:\test\time_shifted\S99GF9\Driver Video\S99GF...,E:\test\time_shifted\S99GF9\ET\S99GF9_VX_et_ra...,ready
31,SHUPW7,VX,E:\test\time_shifted\SHUPW7\Driver Video\SHUPW...,E:\test\time_shifted\SHUPW7\ET\SHUPW7_VX_et_ra...,ready
32,SPKHNL,VX,E:\test\time_shifted\SPKHNL\Driver Video\SPKHN...,E:\test\time_shifted\SPKHNL\ET\SPKHNL_VX_et_ra...,ready
33,TXRE5B,VX,E:\test\time_shifted\TXRE5B\Driver Video\TXRE5...,E:\test\time_shifted\TXRE5B\ET\TXRE5B_VX_et_ra...,ready
34,U83GH3,VX,E:\test\time_shifted\U83GH3\Driver Video\U83GH...,E:\test\time_shifted\U83GH3\ET\U83GH3_VX_et_ra...,ready
35,UY6WA8,VX,E:\test\time_shifted\UY6WA8\Driver Video\UY6WA...,E:\test\time_shifted\UY6WA8\ET\UY6WA8_VX_et_ra...,ready
36,V3SLBM,VX,E:\test\time_shifted\V3SLBM\Driver Video\V3SLB...,E:\test\time_shifted\V3SLBM\ET\V3SLBM_VX_et_ra...,ready
37,VUT5TP,VX,E:\test\time_shifted\VUT5TP\Driver Video\VUT5T...,E:\test\time_shifted\VUT5TP\ET\VUT5TP_VX_et_ra...,ready
38,W3MTYZ,VX,E:\test\time_shifted\W3MTYZ\Driver Video\W3MTY...,E:\test\time_shifted\W3MTYZ\ET\W3MTYZ_VX_et_ra...,ready
39,XJF6R9,VX,E:\test\time_shifted\XJF6R9\Driver Video\XJF6R...,E:\test\time_shifted\XJF6R9\ET\XJF6R9_VX_et_ra...,ready
40,YHYKDQ,VX,E:\test\time_shifted\YHYKDQ\Driver Video\YHYKD...,E:\test\time_shifted\YHYKDQ\ET\YHYKDQ_VX_et_ra...,ready
41,Z8HDMS,VX,E:\test\time_shifted\Z8HDMS\Driver Video\Z8HDM...,E:\test\time_shifted\Z8HDMS\ET\Z8HDMS_VX_et_ra...,ready
42,ZQTXLD,VX,E:\test\time_shifted\ZQTXLD\Driver Video\ZQTXL...,E:\test\time_shifted\ZQTXLD\ET\ZQTXLD_VX_et_ra...,ready

## Manual panel annotation

In [3]:
if 'tool' in globals():
    tool.close()
tool = panel.launch_panel_annotator(
    jobs, annotation_csv=ANNOTATION_CSV,
)

VBox(children=(HTML(value='<b>Manual panel transition annotation</b><br>Times are relative to the first displa…

In [4]:
annotations = panel.load_panel_annotations(ANNOTATION_CSV)
display(panel.summarize_panel_annotations(
    jobs, ANNOTATION_CSV, annotations=annotations,
))

,project,pid,visit,segment_id,discovery_status,driver_panel_off,driver_panel_on,et_scene_panel_off,et_scene_panel_on,event_order_valid,anchors_complete
0,ImBrAid,A7G5SM,VX,main,ready,accepted,accepted,accepted,accepted,True,True
1,ImBrAid,ABVLGQ,VX,main,ready,accepted,accepted,accepted,accepted,True,True
2,ImBrAid,B9NYQ8,VX,main,ready,accepted,accepted,accepted,accepted,True,True
3,ImBrAid,CRVWF9,VX,main,ready,accepted,accepted,accepted,accepted,True,True
4,ImBrAid,CRYSEP,VX,main,ready,accepted,accepted,accepted,accepted,True,True
5,ImBrAid,CU6DM4,VX,main,ready,accepted,accepted,accepted,accepted,True,True
6,ImBrAid,DUJL2L,VX,main,ready,accepted,accepted,accepted,accepted,True,True
7,ImBrAid,E4MKXT,VX,main,ready,accepted,accepted,accepted,accepted,True,True
8,ImBrAid,EASFXM,VX,main,ready,accepted,accepted,accepted,accepted,True,True
9,ImBrAid,FEDZAG,VX,main,ready,accepted,not_visible,accepted,accepted,True,False
10,ImBrAid,FGJK2B,VX,main,ready,accepted,accepted,accepted,accepted,True,True
11,ImBrAid,FLZWD8,VX,main,ready,accepted,accepted,accepted,accepted,True,True
12,ImBrAid,G93LYM,VX,main,ready,accepted,accepted,not_visible,accepted,True,False
13,ImBrAid,GLRNU9,VX,main,ready,accepted,not_visible,accepted,not_visible,True,False
14,ImBrAid,HH5RBX,VX,main,ready,accepted,accepted,not_visible,accepted,True,False
15,ImBrAid,HKJPM3,VX,main,ambiguous_et_scene,accepted,accepted,video_missing_or_ambiguous,video_missing_or_ambiguous,True,False
16,ImBrAid,HNWSPB,VX,main,ready,accepted,accepted,accepted,accepted,True,True
17,ImBrAid,JVC62S,VX,main,ready,accepted,accepted,accepted,accepted,True,True
18,ImBrAid,LGJEFY,VX,main,ready,accepted,accepted,accepted,accepted,True,True
19,ImBrAid,LKK2WT,VX,main,ready,accepted,accepted,accepted,accepted,True,True
20,ImBrAid,MUHKQF,VX,main,ready,accepted,accepted,not_visible,accepted,True,False
21,ImBrAid,N37VFK,VX,main,ready,accepted,accepted,accepted,accepted,True,True
22,ImBrAid,N7C4A6,VX,main,ready,accepted,accepted,accepted,accepted,True,True
23,ImBrAid,NJN65T,VX,main,ready,accepted,accepted,accepted,accepted,True,True
24,ImBrAid,PJ52F4,VX,main,ready,accepted,accepted,accepted,accepted,True,True
25,ImBrAid,Q5ZPCB,VX,main,ready,accepted,accepted,accepted,accepted,True,True
26,ImBrAid,R595WP,VX,main,ready,accepted,accepted,accepted,accepted,True,True
27,ImBrAid,R8YB77,VX,main,ready,accepted,accepted,accepted,accepted,True,True
28,ImBrAid,RYE8J9,VX,main,ready,accepted,accepted,accepted,accepted,True,True
29,ImBrAid,RZKLE8,VX,main,ready,accepted,accepted,accepted,not_visible,True,False
30,ImBrAid,S99GF9,VX,main,ready,accepted,accepted,not_visible,accepted,True,False
31,ImBrAid,SHUPW7,VX,main,ready,accepted,accepted,accepted,accepted,True,True
32,ImBrAid,SPKHNL,VX,main,ready,accepted,accepted,accepted,accepted,True,True
33,ImBrAid,TXRE5B,VX,main,ready,accepted,accepted,accepted,accepted,True,True
34,ImBrAid,U83GH3,VX,main,ready,accepted,accepted,accepted,accepted,True,True
35,ImBrAid,UY6WA8,VX,main,ready,accepted,accepted,accepted,accepted,True,True
36,ImBrAid,V3SLBM,VX,main,ready,accepted,accepted,not_visible,not_visible,True,False
37,ImBrAid,VUT5TP,VX,main,ready,accepted,accepted,accepted,accepted,True,True
38,ImBrAid,W3MTYZ,VX,main,ready,accepted,accepted,accepted,accepted,True,True
39,ImBrAid,XJF6R9,VX,main,ready,accepted,accepted,accepted,accepted,True,True
40,ImBrAid,YHYKDQ,VX,main,ready,accepted,accepted,accepted,accepted,True,True
41,ImBrAid,Z8HDMS,VX,main,ready,accepted,accepted,accepted,accepted,True,True
42,ImBrAid,ZQTXLD,VX,main,ready,accepted,accepted,accepted,accepted,True,True

In [5]:
alignments, issues = alignment.build_driver_et_alignments(
    annotations, video_pairs=jobs,
    drift_warning_ppm=DRIFT_WARNING_PPM,
    drift_reject_ppm=DRIFT_REJECT_PPM,
    offset_only_drift_bound_ppm=OFFSET_ONLY_DRIFT_BOUND_PPM,
    max_pair_uncertainty_s=MAX_PAIR_UNCERTAINTY_S,
)
if OVERWRITE:
    alignment.save_driver_et_alignment_results(
        alignments, issues, alignment_csv=ALIGNMENT_CSV, issues_csv=ISSUES_CSV,
    )
display(alignments[[
    'project', 'pid', 'visit', 'mapping_status', 'anchor_count',
    'usable', 'quality_grade', 'review_required',
    'driver_to_et_raw_drift_ppm', 'mapping_reason', 'warnings',
]])
display(issues)

,project,pid,visit,mapping_status,anchor_count,usable,quality_grade,review_required,driver_to_et_raw_drift_ppm,mapping_reason,warnings
0,ImBrAid,A7G5SM,VX,affine,2,True,B,False,522.924392,two accepted event pairs passed mapping QC,
1,ImBrAid,ABVLGQ,VX,affine,2,True,B,False,507.60176,two accepted event pairs passed mapping QC,
2,ImBrAid,B9NYQ8,VX,affine,2,True,B,False,529.84245,two accepted event pairs passed mapping QC,
3,ImBrAid,CRVWF9,VX,affine,2,True,B,False,528.516717,two accepted event pairs passed mapping QC,
4,ImBrAid,CRYSEP,VX,affine,2,True,A,False,463.093432,two accepted event pairs passed mapping QC,
5,ImBrAid,CU6DM4,VX,affine,2,True,A,False,474.700879,two accepted event pairs passed mapping QC,
6,ImBrAid,DUJL2L,VX,affine,2,True,A,False,479.862923,two accepted event pairs passed mapping QC,
7,ImBrAid,E4MKXT,VX,affine,2,True,A,False,455.066149,two accepted event pairs passed mapping QC,
8,ImBrAid,EASFXM,VX,affine,2,True,A,False,460.496887,two accepted event pairs passed mapping QC,
9,ImBrAid,FEDZAG,VX,offset_only,1,True,C,True,NaN,one paired event; usable with scale fixed to 1...,single anchor cannot estimate clock drift; sca...
10,ImBrAid,FGJK2B,VX,affine,2,True,B,False,519.561111,two accepted event pairs passed mapping QC,
11,ImBrAid,FLZWD8,VX,affine,2,True,B,False,554.270988,two accepted event pairs passed mapping QC,
12,ImBrAid,G93LYM,VX,offset_only,1,True,C,True,NaN,one paired event; usable with scale fixed to 1...,single anchor cannot estimate clock drift; sca...
13,ImBrAid,GLRNU9,VX,offset_only,1,True,C,True,NaN,one paired event; usable with scale fixed to 1...,single anchor cannot estimate clock drift; sca...
14,ImBrAid,HH5RBX,VX,offset_only,1,True,C,True,NaN,one paired event; usable with scale fixed to 1...,single anchor cannot estimate clock drift; sca...
15,ImBrAid,HKJPM3,VX,unavailable,0,False,D,False,NaN,no paired accepted panel anchors,
16,ImBrAid,HNWSPB,VX,review_affine,2,True,C,True,742.777346,at least one accepted anchor has low confidence,at least one accepted anchor has low confidence
17,ImBrAid,JVC62S,VX,invalid_affine,2,False,D,True,-824330.587636,affine coefficients are diagnostic only; hard ...,
18,ImBrAid,LGJEFY,VX,affine,2,True,A,False,489.009185,two accepted event pairs passed mapping QC,
19,ImBrAid,LKK2WT,VX,affine,2,True,B,False,555.894391,two accepted event pairs passed mapping QC,
20,ImBrAid,MUHKQF,VX,offset_only,1,True,C,True,NaN,one paired event; usable with scale fixed to 1...,single anchor cannot estimate clock drift; sca...
21,ImBrAid,N37VFK,VX,affine,2,True,B,False,1485.001143,two accepted event pairs passed mapping QC,
22,ImBrAid,N7C4A6,VX,affine,2,True,B,False,505.955048,two accepted event pairs passed mapping QC,
23,ImBrAid,NJN65T,VX,affine,2,True,A,False,494.984366,two accepted event pairs passed mapping QC,
24,ImBrAid,PJ52F4,VX,affine,2,True,A,False,477.671273,two accepted event pairs passed mapping QC,
25,ImBrAid,Q5ZPCB,VX,affine,2,True,B,False,502.926711,two accepted event pairs passed mapping QC,
26,ImBrAid,R595WP,VX,affine,2,True,A,False,490.917979,two accepted event pairs passed mapping QC,
27,ImBrAid,R8YB77,VX,invalid_affine,2,False,D,True,75583.924552,affine coefficients are diagnostic only; hard ...,
28,ImBrAid,RYE8J9,VX,affine,2,True,A,False,497.496806,two accepted event pairs passed mapping QC,
29,ImBrAid,RZKLE8,VX,offset_only,1,True,C,True,NaN,one paired event; usable with scale fixed to 1...,single anchor cannot estimate clock drift; sca...
30,ImBrAid,S99GF9,VX,offset_only,1,True,C,True,NaN,one paired event; usable with scale fixed to 1...,single anchor cannot estimate clock drift; sca...
31,ImBrAid,SHUPW7,VX,affine,2,True,B,False,548.781025,two accepted event pairs passed mapping QC,
32,ImBrAid,SPKHNL,VX,affine,2,True,B,False,506.990863,two accepted event pairs passed mapping QC,
33,ImBrAid,TXRE5B,VX,affine,2,True,A,False,469.575891,two accepted event pairs passed mapping QC,
34,ImBrAid,U83GH3,VX,affine,2,True,B,False,507.54455,two accepted event pairs passed mapping QC,
35,ImBrAid,UY6WA8,VX,affine,2,True,B,False,547.006478,two accepted event pairs passed mapping QC,
36,ImBrAid,V3SLBM,VX,unavailable,0,False,D,False,NaN,no paired accepted panel anchors,
37,ImBrAid,VUT5TP,VX,affine,2,True,A,False,493.541887,two accepted event pairs passed mapping QC,
38,ImBrAid,W3MTYZ,VX,review_affine,2,True,C,True,-2226.375022,absolute clock drift 2226.4 ppm exceeds review...,absolute clock drift 2226.4 ppm exceeds review...
39,ImBrAid,XJF6R9,VX,affine,2,True,B,False,533.037875,two accepted event pairs passed mapping QC,
40,ImBrAid,YHYKDQ,VX,affine,2,True,A,False,471.399585,two accepted event pairs passed mapping QC,
41,ImBrAid,Z8HDMS,VX,affine,2,True,B,False,506.037061,two accepted event pairs passed mapping QC,
42,ImBrAid,ZQTXLD,VX,affine,2,True,B,False,563.625752,two accepted event pairs passed mapping QC,

,project,pid,visit,segment_id,severity,code,source,event,message
0,ImBrAid,FEDZAG,VX,main,warning,single_anchor_offset_only,,panel_off,single anchor cannot estimate clock drift; sca...
1,ImBrAid,G93LYM,VX,main,warning,single_anchor_offset_only,,panel_on,single anchor cannot estimate clock drift; sca...
2,ImBrAid,GLRNU9,VX,main,warning,single_anchor_offset_only,,panel_off,single anchor cannot estimate clock drift; sca...
3,ImBrAid,HH5RBX,VX,main,warning,single_anchor_offset_only,,panel_on,single anchor cannot estimate clock drift; sca...
4,ImBrAid,HKJPM3,VX,main,warning,no_paired_anchor,,,no panel event has accepted annotations in bot...
5,ImBrAid,HNWSPB,VX,main,warning,low_confidence_anchor,,,at least one accepted anchor has low confidence
6,ImBrAid,JVC62S,VX,main,error,drift_exceeds_reject_threshold,,,absolute clock drift 824330.6 ppm exceeds reje...
7,ImBrAid,MUHKQF,VX,main,warning,single_anchor_offset_only,,panel_on,single anchor cannot estimate clock drift; sca...
8,ImBrAid,R8YB77,VX,main,error,drift_exceeds_reject_threshold,,,absolute clock drift 75583.9 ppm exceeds rejec...
9,ImBrAid,RZKLE8,VX,main,warning,single_anchor_offset_only,,panel_off,single anchor cannot estimate clock drift; sca...
10,ImBrAid,S99GF9,VX,main,warning,single_anchor_offset_only,,panel_on,single anchor cannot estimate clock drift; sca...
11,ImBrAid,V3SLBM,VX,main,warning,no_paired_anchor,,,no panel event has accepted annotations in bot...
12,ImBrAid,W3MTYZ,VX,main,warning,drift_requires_review,,,absolute clock drift 2226.4 ppm exceeds review...