# 03 · ET raw → Eyeball alignment

Fit `eyeball = intercept + scale * et_raw` from pupil content. Publication files are generated only in step 10.

In [1]:
import importlib
import sys
from pathlib import Path

from IPython.display import display

for PROJECT_ROOT in (Path.cwd().resolve(), *Path.cwd().resolve().parents):
    if (PROJECT_ROOT / 'helpers').is_dir():
        sys.path.insert(0, str(PROJECT_ROOT))
        break
else:
    raise FileNotFoundError('Could not locate the BIGPROJECT/helpers folder')

from helpers.project_config import load_project_config
from helpers.sync_quality import et_eyeball_alignment as alignment
importlib.reload(alignment)

CONFIG = load_project_config(PROJECT_ROOT / 'ImBrAid' / 'config.json')
PROJECT_NAME = CONFIG.project
DATA_ROOT = CONFIG.path('paths', 'processing_data_root')
PUPIL_CSV_ROOT = CONFIG.path('paths', 'eyeball_work_root') / 'pupil_sizes'
ET_SUBFOLDER = CONFIG.value('modalities', 'eyeball_source_subfolder')
ALIGNMENT_CSV = CONFIG.path('files', 'et_eyeball_alignment_csv')
WINDOWS_CSV = CONFIG.path('files', 'et_eyeball_windows_csv')
ISSUES_CSV = CONFIG.path('files', 'et_eyeball_issues_csv')
OVERWRITE = True
PARTICIPANTS = None
VISITS = None
WINDOW_S = 90.0
STEP_S = 45.0
LOCAL_RESIDUAL_SEARCH_RADIUS_S = 15.0

In [2]:
jobs = alignment.discover_et_eyeball_jobs(
    DATA_ROOT, PUPIL_CSV_ROOT, PROJECT_NAME, et_subfolder=ET_SUBFOLDER,
    participants=PARTICIPANTS, visits=VISITS,
)
display(jobs)

,project,pid,visit,et_recording_path,pupil_csv_path,et_candidate_count,pupil_csv_candidate_count,discovery_status,et_candidates,pupil_csv_candidates
0,ImBrAid,A7G5SM,VX,E:\test\time_shifted\A7G5SM\ET\A7G5SM_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\A...,1,1,ready,E:\test\time_shifted\A7G5SM\ET\A7G5SM_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\A...
1,ImBrAid,ABVLGQ,VX,E:\test\time_shifted\ABVLGQ\ET\ABVLGQ_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\A...,1,1,ready,E:\test\time_shifted\ABVLGQ\ET\ABVLGQ_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\A...
2,ImBrAid,B9NYQ8,VX,E:\test\time_shifted\B9NYQ8\ET\B9NYQ8_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\B...,1,1,ready,E:\test\time_shifted\B9NYQ8\ET\B9NYQ8_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\B...
3,ImBrAid,CRVWF9,VX,E:\test\time_shifted\CRVWF9\ET\CRVWF9_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\C...,1,1,ready,E:\test\time_shifted\CRVWF9\ET\CRVWF9_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\C...
4,ImBrAid,CRYSEP,VX,E:\test\time_shifted\CRYSEP\ET\CRYSEP_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\C...,1,1,ready,E:\test\time_shifted\CRYSEP\ET\CRYSEP_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\C...
5,ImBrAid,CU6DM4,VX,E:\test\time_shifted\CU6DM4\ET\CU6DM4_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\C...,1,1,ready,E:\test\time_shifted\CU6DM4\ET\CU6DM4_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\C...
6,ImBrAid,DUJL2L,VX,E:\test\time_shifted\DUJL2L\ET\DUJL2L_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\D...,1,1,ready,E:\test\time_shifted\DUJL2L\ET\DUJL2L_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\D...
7,ImBrAid,E4MKXT,VX,E:\test\time_shifted\E4MKXT\ET\E4MKXT_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\E...,1,1,ready,E:\test\time_shifted\E4MKXT\ET\E4MKXT_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\E...
8,ImBrAid,EASFXM,VX,E:\test\time_shifted\EASFXM\ET\EASFXM_VX_et_raw,,1,0,missing_pupil_csv,E:\test\time_shifted\EASFXM\ET\EASFXM_VX_et_raw,
9,ImBrAid,FEDZAG,VX,E:\test\time_shifted\FEDZAG\ET\FEDZAG_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\F...,1,1,ready,E:\test\time_shifted\FEDZAG\ET\FEDZAG_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\F...
10,ImBrAid,FGJK2B,VX,E:\test\time_shifted\FGJK2B\ET\FGJK2B_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\F...,1,1,ready,E:\test\time_shifted\FGJK2B\ET\FGJK2B_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\F...
11,ImBrAid,FLZWD8,VX,E:\test\time_shifted\FLZWD8\ET\FLZWD8_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\F...,1,1,ready,E:\test\time_shifted\FLZWD8\ET\FLZWD8_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\F...
12,ImBrAid,G93LYM,VX,E:\test\time_shifted\G93LYM\ET\G93LYM_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\G...,1,1,ready,E:\test\time_shifted\G93LYM\ET\G93LYM_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\G...
13,ImBrAid,GLRNU9,VX,E:\test\time_shifted\GLRNU9\ET\GLRNU9_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\G...,1,1,ready,E:\test\time_shifted\GLRNU9\ET\GLRNU9_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\G...
14,ImBrAid,HH5RBX,VX,E:\test\time_shifted\HH5RBX\ET\HH5RBX_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\H...,1,1,ready,E:\test\time_shifted\HH5RBX\ET\HH5RBX_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\H...
15,ImBrAid,HKJPM3,VX,,,2,0,missing_pupil_csv,E:\test\time_shifted\HKJPM3\ET\HKJPM3_VX_et_ra...,
16,ImBrAid,HNWSPB,VX,E:\test\time_shifted\HNWSPB\ET\HNWSPB_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\H...,1,1,ready,E:\test\time_shifted\HNWSPB\ET\HNWSPB_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\H...
17,ImBrAid,JVC62S,VX,E:\test\time_shifted\JVC62S\ET\JVC62S_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\J...,1,1,ready,E:\test\time_shifted\JVC62S\ET\JVC62S_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\J...
18,ImBrAid,LGJEFY,VX,E:\test\time_shifted\LGJEFY\ET\LGJEFY_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\L...,1,1,ready,E:\test\time_shifted\LGJEFY\ET\LGJEFY_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\L...
19,ImBrAid,LKK2WT,VX,E:\test\time_shifted\LKK2WT\ET\LKK2WT_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\L...,1,1,ready,E:\test\time_shifted\LKK2WT\ET\LKK2WT_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\L...
20,ImBrAid,MUHKQF,VX,E:\test\time_shifted\MUHKQF\ET\MUHKQF_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\M...,1,1,ready,E:\test\time_shifted\MUHKQF\ET\MUHKQF_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\M...
21,ImBrAid,N37VFK,VX,E:\test\time_shifted\N37VFK\ET\N37VFK_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\N...,1,1,ready,E:\test\time_shifted\N37VFK\ET\N37VFK_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\N...
22,ImBrAid,N7C4A6,VX,E:\test\time_shifted\N7C4A6\ET\N7C4A6_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\N...,1,1,ready,E:\test\time_shifted\N7C4A6\ET\N7C4A6_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\N...
23,ImBrAid,NJN65T,VX,E:\test\time_shifted\NJN65T\ET\NJN65T_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\N...,1,1,ready,E:\test\time_shifted\NJN65T\ET\NJN65T_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\N...
24,ImBrAid,PJ52F4,VX,E:\test\time_shifted\PJ52F4\ET\PJ52F4_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\P...,1,1,ready,E:\test\time_shifted\PJ52F4\ET\PJ52F4_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\P...
25,ImBrAid,Q5ZPCB,VX,E:\test\time_shifted\Q5ZPCB\ET\Q5ZPCB_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\Q...,1,1,ready,E:\test\time_shifted\Q5ZPCB\ET\Q5ZPCB_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\Q...
26,ImBrAid,R595WP,VX,E:\test\time_shifted\R595WP\ET\R595WP_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\R...,1,1,ready,E:\test\time_shifted\R595WP\ET\R595WP_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\R...
27,ImBrAid,R8YB77,VX,E:\test\time_shifted\R8YB77\ET\R8YB77_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\R...,1,1,ready,E:\test\time_shifted\R8YB77\ET\R8YB77_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\R...
28,ImBrAid,RYE8J9,VX,E:\test\time_shifted\RYE8J9\ET\RYE8J9_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\R...,1,1,ready,E:\test\time_shifted\RYE8J9\ET\RYE8J9_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\R...
29,ImBrAid,RZKLE8,VX,E:\test\time_shifted\RZKLE8\ET\RZKLE8_VX_et_raw,,1,0,missing_pupil_csv,E:\test\time_shifted\RZKLE8\ET\RZKLE8_VX_et_raw,
30,ImBrAid,S99GF9,VX,E:\test\time_shifted\S99GF9\ET\S99GF9_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\S...,1,1,ready,E:\test\time_shifted\S99GF9\ET\S99GF9_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\S...
31,ImBrAid,SHUPW7,VX,E:\test\time_shifted\SHUPW7\ET\SHUPW7_VX_et_raw,,1,0,missing_pupil_csv,E:\test\time_shifted\SHUPW7\ET\SHUPW7_VX_et_raw,
32,ImBrAid,SPKHNL,VX,E:\test\time_shifted\SPKHNL\ET\SPKHNL_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\S...,1,1,ready,E:\test\time_shifted\SPKHNL\ET\SPKHNL_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\S...
33,ImBrAid,TXRE5B,VX,E:\test\time_shifted\TXRE5B\ET\TXRE5B_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\T...,1,1,ready,E:\test\time_shifted\TXRE5B\ET\TXRE5B_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\T...
34,ImBrAid,U83GH3,VX,E:\test\time_shifted\U83GH3\ET\U83GH3_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\U...,1,1,ready,E:\test\time_shifted\U83GH3\ET\U83GH3_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\U...
35,ImBrAid,UY6WA8,VX,E:\test\time_shifted\UY6WA8\ET\UY6WA8_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\U...,1,1,ready,E:\test\time_shifted\UY6WA8\ET\UY6WA8_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\U...
36,ImBrAid,V3SLBM,VX,E:\test\time_shifted\V3SLBM\ET\V3SLBM_VX_et_raw,,1,0,missing_pupil_csv,E:\test\time_shifted\V3SLBM\ET\V3SLBM_VX_et_raw,
37,ImBrAid,VUT5TP,VX,E:\test\time_shifted\VUT5TP\ET\VUT5TP_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\V...,1,1,ready,E:\test\time_shifted\VUT5TP\ET\VUT5TP_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\V...
38,ImBrAid,W3MTYZ,VX,E:\test\time_shifted\W3MTYZ\ET\W3MTYZ_VX_et_raw,,1,0,missing_pupil_csv,E:\test\time_shifted\W3MTYZ\ET\W3MTYZ_VX_et_raw,
39,ImBrAid,XJF6R9,VX,E:\test\time_shifted\XJF6R9\ET\XJF6R9_VX_et_raw,,1,0,missing_pupil_csv,E:\test\time_shifted\XJF6R9\ET\XJF6R9_VX_et_raw,
40,ImBrAid,YHYKDQ,VX,E:\test\time_shifted\YHYKDQ\ET\YHYKDQ_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\Y...,1,1,ready,E:\test\time_shifted\YHYKDQ\ET\YHYKDQ_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\Y...
41,ImBrAid,Z8HDMS,VX,E:\test\time_shifted\Z8HDMS\ET\Z8HDMS_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\Z...,1,1,ready,E:\test\time_shifted\Z8HDMS\ET\Z8HDMS_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\Z...
42,ImBrAid,ZQTXLD,VX,E:\test\time_shifted\ZQTXLD\ET\ZQTXLD_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\Z...,1,1,ready,E:\test\time_shifted\ZQTXLD\ET\ZQTXLD_VX_et_raw,E:\test\processed\Eyeball_Videos\pupil_sizes\Z...

In [3]:
alignments, windows, issues = alignment.build_et_eyeball_alignments(
    jobs, window_s=WINDOW_S, step_s=STEP_S,
    local_residual_search_radius_s=LOCAL_RESIDUAL_SEARCH_RADIUS_S,
)
if OVERWRITE:
    alignment.save_et_eyeball_alignment_results(
        alignments, windows, issues, alignment_csv=ALIGNMENT_CSV,
        windows_csv=WINDOWS_CSV, issues_csv=ISSUES_CSV,
    )
display(alignments[[
    'pid', 'visit', 'mapping_status', 'usable', 'quality_grade',
    'review_required', 'intercept_s', 'scale', 'drift_ppm',
    'n_good_windows', 'fit_residual_p95_s', 'mapping_reason',
]])
display(issues[issues['severity'].ne('info')])

,pid,visit,mapping_status,usable,quality_grade,review_required,intercept_s,scale,drift_ppm,n_good_windows,fit_residual_p95_s,mapping_reason
0,A7G5SM,VX,content_affine,True,A,False,-1.249187,1.000016,16.295480,59.0,0.007920,local pupil-content windows
1,ABVLGQ,VX,content_affine,True,A,False,-2.600542,1.000002,2.459125,60.0,0.024313,local pupil-content windows
2,B9NYQ8,VX,content_affine,True,A,False,-2.292557,1.000014,14.369381,57.0,0.021553,local pupil-content windows
3,CRVWF9,VX,content_affine,True,A,False,-2.589389,1.000017,16.928546,55.0,0.017197,local pupil-content windows
4,CRYSEP,VX,content_affine,True,A,False,-2.122103,1.000006,6.362459,60.0,0.009737,local pupil-content windows
5,CU6DM4,VX,content_affine,True,A,False,-2.996542,1.000012,12.392064,63.0,0.005953,local pupil-content windows
6,DUJL2L,VX,content_affine,True,A,False,-2.733734,1.000006,6.023529,61.0,0.005713,local pupil-content windows
7,E4MKXT,VX,content_affine,True,A,False,-1.769248,1.000004,4.272418,60.0,0.005239,local pupil-content windows
8,EASFXM,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,NaN,missing_pupil_csv
9,FEDZAG,VX,invalid_affine,False,D,True,NaN,NaN,NaN,NaN,NaN,local lag residual P95 0.926 s exceeds hard li...
10,FGJK2B,VX,content_affine,True,A,False,-1.639430,0.999995,-4.561251,59.0,0.015957,local pupil-content windows
11,FLZWD8,VX,content_affine,True,A,False,-1.975437,1.000002,1.989010,59.0,0.015482,local pupil-content windows
12,G93LYM,VX,content_affine,True,A,False,-1.640193,0.999989,-10.920356,39.0,0.024415,local pupil-content windows
13,GLRNU9,VX,content_affine,True,A,False,-2.911318,1.000007,7.259659,47.0,0.025020,local pupil-content windows
14,HH5RBX,VX,content_review,True,C,True,-2.297584,1.000003,3.178697,25.0,0.010589,local pupil-content windows; aligned pupil amp...
15,HKJPM3,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,NaN,missing_pupil_csv
16,HNWSPB,VX,content_affine,True,A,False,-1.544320,1.000017,17.472649,57.0,0.012262,local pupil-content windows
17,JVC62S,VX,content_affine,True,B,False,-2.273089,1.000020,20.374073,11.0,0.014384,local pupil-content windows
18,LGJEFY,VX,content_affine,True,A,False,-2.603924,1.000005,5.241787,59.0,0.008385,local pupil-content windows
19,LKK2WT,VX,content_affine,True,A,False,-2.055296,1.000014,13.642564,59.0,0.024674,local pupil-content windows
20,MUHKQF,VX,content_affine,True,A,False,-2.489986,1.000028,28.168856,35.0,0.006593,local pupil-content windows
21,N37VFK,VX,eye_conflict,False,D,True,NaN,NaN,NaN,NaN,NaN,reliable left/right mappings disagree
22,N7C4A6,VX,content_affine,True,A,False,-4.021214,1.000010,10.406518,60.0,0.008038,local pupil-content windows
23,NJN65T,VX,content_affine,True,A,False,-1.065325,1.000027,27.406616,59.0,0.030366,local pupil-content windows
24,PJ52F4,VX,content_affine,True,A,False,-1.745076,1.000011,10.511957,60.0,0.007584,local pupil-content windows
25,Q5ZPCB,VX,content_affine,True,A,False,-2.086684,1.000018,17.709759,60.0,0.009941,local pupil-content windows
26,R595WP,VX,content_affine,True,A,False,-2.756327,1.000014,14.005892,60.0,0.016067,local pupil-content windows
27,R8YB77,VX,content_affine,True,A,False,-2.158372,1.000026,25.528274,59.0,0.068794,local pupil-content windows
28,RYE8J9,VX,content_affine,True,A,False,-2.589454,1.000016,16.098001,61.0,0.007362,local pupil-content windows
29,RZKLE8,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,NaN,missing_pupil_csv
30,S99GF9,VX,content_affine,True,A,False,-0.984586,1.000008,8.238815,56.0,0.015838,local pupil-content windows
31,SHUPW7,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,NaN,missing_pupil_csv
32,SPKHNL,VX,content_affine,True,A,False,-1.454736,1.000007,6.813580,60.0,0.014052,local pupil-content windows
33,TXRE5B,VX,content_affine,True,A,False,-1.957991,1.000004,4.299043,58.0,0.008799,local pupil-content windows
34,U83GH3,VX,content_affine,True,A,False,-1.976668,1.000011,11.402913,61.0,0.011330,local pupil-content windows
35,UY6WA8,VX,content_affine,True,A,False,-3.267255,1.000008,7.913364,60.0,0.009090,local pupil-content windows
36,V3SLBM,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,NaN,missing_pupil_csv
37,VUT5TP,VX,content_affine,True,A,False,-2.049067,1.000006,6.143198,60.0,0.008656,local pupil-content windows
38,W3MTYZ,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,NaN,missing_pupil_csv
39,XJF6R9,VX,unavailable,False,D,True,NaN,NaN,NaN,NaN,NaN,missing_pupil_csv
40,YHYKDQ,VX,content_affine,True,A,False,-3.022257,1.000014,13.757205,60.0,0.008059,local pupil-content windows
41,Z8HDMS,VX,content_affine,True,A,False,-1.661910,1.000008,8.243145,61.0,0.013624,local pupil-content windows
42,ZQTXLD,VX,content_affine,True,A,False,-2.327137,1.000018,17.896887,61.0,0.031052,local pupil-content windows

,project,pid,visit,severity,code,message
0,ImBrAid,EASFXM,VX,error,discovery_not_ready,missing_pupil_csv
1,ImBrAid,FEDZAG,VX,error,invalid_content_mapping,local lag residual P95 0.926 s exceeds hard li...
2,ImBrAid,FEDZAG,VX,warning,fit_qc,local lag residual P95 0.926 s exceeds hard limit
3,ImBrAid,FEDZAG,VX,warning,fit_qc,local lag residual P95 0.922 s exceeds hard limit
4,ImBrAid,HH5RBX,VX,warning,weak_amplitude_relation,aligned pupil amplitudes have weak global line...
5,ImBrAid,HH5RBX,VX,warning,fit_qc,fewer than 10% of candidate windows passed QC
6,ImBrAid,HH5RBX,VX,warning,fit_qc,good windows cover less than 25% of the shared...
7,ImBrAid,HKJPM3,VX,error,discovery_not_ready,missing_pupil_csv
8,ImBrAid,JVC62S,VX,warning,fit_qc,only 1 good local window(s); drift is not esti...
9,ImBrAid,N37VFK,VX,error,left_right_mapping_conflict,left/right mappings differ by 18.818 s and 0.0...
10,ImBrAid,N37VFK,VX,warning,fit_qc,absolute clock drift 3461.8 ppm requires review
11,ImBrAid,N37VFK,VX,warning,fit_qc,fewer than 10% of candidate windows passed QC
12,ImBrAid,N37VFK,VX,warning,fit_qc,only 1 good local window(s); drift is not esti...
13,ImBrAid,RZKLE8,VX,error,discovery_not_ready,missing_pupil_csv
14,ImBrAid,SHUPW7,VX,error,discovery_not_ready,missing_pupil_csv
15,ImBrAid,V3SLBM,VX,error,discovery_not_ready,missing_pupil_csv
16,ImBrAid,W3MTYZ,VX,error,discovery_not_ready,missing_pupil_csv
17,ImBrAid,XJF6R9,VX,error,discovery_not_ready,missing_pupil_csv