# 10 · Compact synchronized publication export

Export each available modality independently. Missing Eyeball, DriverVideo, or IDUN inputs do not block the others.

Apply accepted affine clock mappings to all finite native timestamps, including extrapolation beyond their observed/fitted support. Support bounds and available support counts remain QC information. No new mapping is fitted. Rerun this notebook before Step 11 to replace earlier CSVs whose derived timestamps were blank outside support.

In [1]:
import importlib
import sys
from pathlib import Path

import pandas as pd
from IPython.display import display

for PROJECT_ROOT in (Path.cwd().resolve(), *Path.cwd().resolve().parents):
    if (PROJECT_ROOT / 'helpers').is_dir():
        sys.path.insert(0, str(PROJECT_ROOT))
        break
else:
    raise FileNotFoundError('Could not locate the BIGPROJECT/helpers folder')

from helpers.project_config import load_project_config
from helpers.sync_quality import driver_lsl_alignment as driver_lsl
from helpers.sync_quality import driver_timestamp_export as driver_export
from helpers.sync_quality import eyeball_time_table as eyeball_export
from helpers.sync_quality import idun_lsl_alignment as idun_export
importlib.reload(driver_lsl)
importlib.reload(driver_export)
importlib.reload(eyeball_export)
importlib.reload(idun_export)

CONFIG = load_project_config(PROJECT_ROOT / 'ImBrAid' / 'config.json')
DRIVER_LANDMARK_ROOT = CONFIG.path('paths', 'driver_landmark_root')
PUBLICATION_ROOT = CONFIG.path('paths', 'publication_root')
EYEBALL_OUTPUT_DIR = PUBLICATION_ROOT / 'Eyeball'
IDUN_OUTPUT_DIR = PUBLICATION_ROOT / 'IDUN'
DRIVER_OUTPUT_DIR = PUBLICATION_ROOT / 'DriverVideo'
ET_LSL_CSV = CONFIG.path('files', 'et_lsl_alignment_csv')
ET_EYEBALL_CSV = CONFIG.path('files', 'et_eyeball_alignment_csv')
DRIVER_ET_CSV = CONFIG.path('files', 'driver_et_alignment_csv')
IDUN_LSL_CSV = CONFIG.path('files', 'idun_lsl_alignment_csv')
EYEBALL_SUMMARY_CSV = CONFIG.path('files', 'eyeball_export_summary_csv')
DRIVER_SUMMARY_CSV = CONFIG.path('files', 'driver_video_export_summary_csv')
IDUN_SUMMARY_CSV = CONFIG.path('files', 'idun_export_summary_csv')
IDUN_ISSUES_CSV = CONFIG.path('files', 'idun_export_issues_csv')
OVERWRITE = True

## Available modalities

In [2]:
print('Each available modality will be exported independently.')

Each available modality will be exported independently.

## Eyeball and DriverVideo publication files

In [3]:
eyeball_summary = None
if ET_EYEBALL_CSV.is_file() and ET_LSL_CSV.is_file():
    et_eyeball = pd.read_csv(ET_EYEBALL_CSV, dtype=str, keep_default_na=False)
    et_lsl = pd.read_csv(ET_LSL_CSV, dtype=str, keep_default_na=False)
    eyeball_summary = eyeball_export.export_aligned_eyeball_csvs(
        et_eyeball, et_lsl, output_dir=EYEBALL_OUTPUT_DIR,
        overwrite=OVERWRITE,
    )
    eyeball_export.save_eyeball_timestamp_summary(
        eyeball_summary, EYEBALL_SUMMARY_CSV,
    )
    display(eyeball_summary)
else:
    print('Eyeball skipped: its mapping files are absent.')

driver_summary = None
if DRIVER_ET_CSV.is_file() and ET_LSL_CSV.is_file() and DRIVER_LANDMARK_ROOT.is_dir():
    driver_summary = driver_export.export_publication_from_synchronized_landmarks(
        landmark_root=DRIVER_LANDMARK_ROOT,
        driver_et_alignment_csv=DRIVER_ET_CSV,
        et_lsl_alignment_csv=ET_LSL_CSV, output_root=DRIVER_OUTPUT_DIR,
        overwrite=OVERWRITE,
        project=CONFIG.project,
    )
    driver_export.save_driver_timestamp_summary(
        driver_summary, DRIVER_SUMMARY_CSV,
    )
    display(driver_summary)
else:
    print('DriverVideo skipped: its landmarks or mapping files are absent.')

,project,pid,visit,processing_status,reason,source_pupil_csv,output_pupil_csv,rows,aligned_rows,aligned_fraction,...,common_et_support_start_s,common_et_support_end_s,et_raw_start_s,et_raw_end_s,lsl_start_s,lsl_end_s,quality_grade,review_required,et_eyeball_mapping_status,et_lsl_mapping_status
0,ImBrAid,A7G5SM,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\A...,E:\test\DatasetForPublish\preprocessed_data\Ey...,110750.0,110750.0,1.0,...,20.299319,2122.804526,1.249167,2716.824915,14859.148000,17574.704169,B,False,content_affine,content_affine
1,ImBrAid,ABVLGQ,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\A...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136225.0,136225.0,1.0,...,17.708200,2724.351976,2.600536,2732.013824,25562.708763,28292.147787,A,False,content_affine,content_affine
2,ImBrAid,B9NYQ8,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\B...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136163.0,136163.0,1.0,...,20.232971,2730.590342,2.292524,2730.453322,20056.637128,22784.822947,A,False,content_affine,content_affine
3,ImBrAid,CRVWF9,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\C...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136242.0,136242.0,1.0,...,32.602297,2716.329492,2.589345,2732.106138,18828.975304,21558.516656,A,False,content_affine,content_affine
4,ImBrAid,CRYSEP,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\C...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136738.0,136738.0,1.0,...,24.353139,2733.477694,2.122090,2741.824658,105887.736002,108627.467183,A,False,content_affine,content_affine
5,ImBrAid,CU6DM4,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\C...,E:\test\DatasetForPublish\preprocessed_data\Ey...,143883.0,143883.0,1.0,...,66.913537,2876.537893,2.996505,2885.860780,608599.691833,611482.584360,A,False,content_affine,content_affine
6,ImBrAid,DUJL2L,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\D...,E:\test\DatasetForPublish\preprocessed_data\Ey...,138401.0,138401.0,1.0,...,13.954841,2775.919925,2.733717,2775.777014,624581.197639,627354.271298,A,False,content_affine,content_affine
7,ImBrAid,E4MKXT,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\E...,E:\test\DatasetForPublish\preprocessed_data\Ey...,137988.0,137988.0,1.0,...,47.644099,2755.127816,1.769241,2766.517429,89253.384795,92018.153743,A,False,content_affine,content_affine
8,ImBrAid,EASFXM,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unavailable,content_affine
9,ImBrAid,FEDZAG,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,E:\test\processed\Eyeball_Videos\pupil_sizes\F...,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,invalid_affine,content_affine
10,ImBrAid,FGJK2B,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\F...,E:\test\DatasetForPublish\preprocessed_data\Ey...,117056.0,117056.0,1.0,...,1.979465,2516.600223,1.639438,2708.791786,9991.654800,12698.792087,B,False,content_affine,content_affine
11,ImBrAid,FLZWD8,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\F...,E:\test\DatasetForPublish\preprocessed_data\Ey...,135759.0,135759.0,1.0,...,47.781998,2722.261702,1.975433,2722.070023,102710.950640,105431.067255,A,False,content_affine,content_affine
12,ImBrAid,G93LYM,VX,unavailable,ValueError: ET/LSL mapping is not usable,E:\test\processed\Eyeball_Videos\pupil_sizes\G...,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,content_affine,unavailable
13,ImBrAid,GLRNU9,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\G...,E:\test\DatasetForPublish\preprocessed_data\Ey...,113047.0,113047.0,1.0,...,0.015876,2266.477720,2.911297,2267.914854,4229.705654,6494.727187,A,False,content_affine,content_affine
14,ImBrAid,HH5RBX,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\H...,E:\test\DatasetForPublish\preprocessed_data\Ey...,130525.0,130525.0,1.0,...,0.119289,2618.356997,2.297576,2621.418251,14678.140068,17298.105521,C,True,content_review,content_affine
15,ImBrAid,HKJPM3,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unavailable,unavailable
16,ImBrAid,HNWSPB,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\H...,E:\test\DatasetForPublish\preprocessed_data\Ey...,106393.0,106393.0,1.0,...,0.079265,1790.812218,1.544293,2595.618968,8832.925153,11427.032348,B,False,content_affine,content_affine
17,ImBrAid,JVC62S,VX,unavailable,ValueError: ET/LSL mapping is not usable,E:\test\processed\Eyeball_Videos\pupil_sizes\J...,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,content_affine,unavailable
18,ImBrAid,LGJEFY,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\L...,E:\test\DatasetForPublish\preprocessed_data\Ey...,135409.0,135409.0,1.0,...,0.009662,2707.608289,2.603910,2715.669689,613469.961412,616183.055192,A,False,content_affine,content_affine
19,ImBrAid,LKK2WT,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\L...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136492.0,136492.0,1.0,...,18.389135,2740.248453,2.055268,2753.897725,14766.220774,17518.080998,B,False,content_affine,content_affine
20,ImBrAid,MUHKQF,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\M...,E:\test\DatasetForPublish\preprocessed_data\Ey...,80401.0,80401.0,1.0,...,0.001032,1614.862725,2.489916,1614.708653,99021.526801,100633.780880,A,False,content_affine,content_affine
21,ImBrAid,N37VFK,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,E:\test\processed\Eyeball_Videos\pupil_sizes\N...,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eye_conflict,unavailable
22,ImBrAid,N7C4A6,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\N...,E:\test\DatasetForPublish\preprocessed_data\Ey...,113333.0,113333.0,1.0,...,9.654077,2727.846039,4.021172,2734.792755,20564.851001,23295.614054,B,False,content_affine,content_affine
23,ImBrAid,NJN65T,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\N...,E:\test\DatasetForPublish\preprocessed_data\Ey...,134875.0,134875.0,1.0,...,12.550796,2753.710657,1.065296,2753.409863,18870.206810,21622.572596,B,False,content_affine,content_affine
24,ImBrAid,PJ52F4,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\P...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136448.0,136448.0,1.0,...,18.869999,2727.177015,1.745057,2735.656319,19407.275887,22141.214230,A,False,content_affine,content_affine
25,ImBrAid,Q5ZPCB,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\Q...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136674.0,136674.0,1.0,...,43.308565,2734.055921,2.086647,2741.658130,25405.817527,28145.418467,A,False,content_affine,content_affine
26,ImBrAid,R595WP,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\R...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136369.0,136369.0,1.0,...,20.508447,2729.554867,2.756289,2735.078020,111785.422631,114517.771110,A,False,content_affine,content_affine
27,ImBrAid,R8YB77,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\R...,E:\test\DatasetForPublish\preprocessed_data\Ey...,119818.0,119818.0,1.0,...,15.029340,1991.763302,2.158317,2772.643146,79114.681250,81885.193997,B,False,content_affine,content_affine
28,ImBrAid,RYE8J9,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\R...,E:\test\DatasetForPublish\preprocessed_data\Ey...,139339.0,139339.0,1.0,...,87.228476,2781.628108,2.589413,2794.424470,13435.605544,16227.464550,A,False,content_affine,content_affine
29,ImBrAid,RZKLE8,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unavailable,content_affine
30,ImBrAid,S99GF9,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\S...,E:\test\DatasetForPublish\preprocessed_data\Ey...,110481.0,110481.0,1.0,...,0.058653,2580.026438,0.984577,2580.026329,15216.231015,17795.290896,B,False,content_affine,content_affine
31,ImBrAid,SHUPW7,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unavailable,content_affine
32,ImBrAid,SPKHNL,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\S...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136367.0,136367.0,1.0,...,19.613954,2720.748493,1.454726,2733.736109,2660.230593,5392.533715,A,False,content_affine,content_affine
33,ImBrAid,TXRE5B,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\T...,E:\test\DatasetForPublish\preprocessed_data\Ey...,134278.0,134278.0,1.0,...,0.000164,2681.996881,1.957983,2692.386416,7583.596008,10274.048490,A,False,content_affine,content_affine
34,ImBrAid,U83GH3,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\U...,E:\test\DatasetForPublish\preprocessed_data\Ey...,138129.0,138129.0,1.0,...,62.357054,2759.376022,1.976645,2769.545087,6894.894221,9662.484348,A,False,content_affine,content_affine
35,ImBrAid,UY6WA8,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\U...,E:\test\DatasetForPublish\preprocessed_data\Ey...,137139.0,137139.0,1.0,...,50.351131,2740.746010,3.267229,2751.005485,7407.256724,10155.014661,A,False,content_affine,content_affine
36,ImBrAid,V3SLBM,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unavailable,unavailable
37,ImBrAid,VUT5TP,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\V...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136858.0,136858.0,1.0,...,22.822365,2735.879515,2.049055,2744.172209,90318.741689,93060.889895,A,False,content_affine,content_affine
38,ImBrAid,W3MTYZ,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unavailable,unavailable
39,ImBrAid,XJF6R9,VX,unavailable,ValueError: ET/Eyeball mapping is not usable,,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unavailable,content_affine
40,ImBrAid,YHYKDQ,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\Y...,E:\test\DatasetForPublish\preprocessed_data\Ey...,136585.0,136585.0,1.0,...,7.533237,2729.492261,3.022215,2739.664567,27905.980813,30642.646311,A,False,content_affine,content_affine
41,ImBrAid,Z8HDMS,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\Z...,E:\test\DatasetForPublish\preprocessed_data\Ey...,138583.0,138583.0,1.0,...,70.662494,2768.942862,1.661897,2778.379008,24359.446242,27136.187925,A,False,content_affine,content_affine
42,ImBrAid,ZQTXLD,VX,written,,E:\test\processed\Eyeball_Videos\pupil_sizes\Z...,E:\test\DatasetForPublish\preprocessed_data\Ey...,143100.0,143100.0,1.0,...,129.377861,2851.185757,2.327096,2869.475782,1861.715012,4728.887417,A,False,content_affine,content_affine

Found 43 Driver publication job(s).
[1/43] A7G5SM_VX_driver_video_face_pose_landmarks.csv
[2/43] ABVLGQ_VX_driver_video_face_pose_landmarks.csv
[3/43] B9NYQ8_VX_driver_video_face_pose_landmarks.csv
[4/43] CRVWF9_VX_driver_video_face_pose_landmarks.csv
[5/43] CRYSEP_VX_driver_video_face_pose_landmarks.csv
[6/43] CU6DM4_VX_driver_video_face_pose_landmarks.csv
[7/43] DUJL2L_VX_driver_video_face_pose_landmarks.csv
[8/43] E4MKXT_VX_driver_video_face_pose_landmarks.csv
[9/43] EASFXM_VX_driver_video_face_pose_landmarks.csv
[10/43] FEDZAG_VX_driver_video_face_pose_landmarks.csv
[11/43] FGJK2B_VX_driver_video_face_pose_landmarks.csv
[12/43] FLZWD8_VX_driver_video_face_pose_landmarks.csv
[13/43] G93LYM_VX_driver_video_face_pose_landmarks.csv
  ERROR: ET/LSL mapping is not usable
[14/43] GLRNU9_VX_driver_video_face_pose_landmarks.csv
[15/43] HH5RBX_VX_driver_video_face_pose_landmarks.csv
[16/43] HKJPM3_VX_driver_video_face_pose_landmarks.csv
  ERROR: Driver/ET mapping is not usable
[17/43] HNWSPB_VX_driver_video_face_pose_landmarks.csv
[18/43] JVC62S_VX_driver_video_face_pose_landmarks.csv
  ERROR: Driver/ET mapping is not usable
[19/43] LGJEFY_VX_driver_video_face_pose_landmarks.csv
[20/43] LKK2WT_VX_driver_video_face_pose_landmarks.csv
[21/43] MUHKQF_VX_driver_video_face_pose_landmarks.csv
[22/43] N37VFK_VX_driver_video_face_pose_landmarks.csv
  ERROR: ET/LSL mapping is not usable
[23/43] N7C4A6_VX_driver_video_face_pose_landmarks.csv
[24/43] NJN65T_VX_driver_video_face_pose_landmarks.csv
[25/43] PJ52F4_VX_driver_video_face_pose_landmarks.csv
[26/43] Q5ZPCB_VX_driver_video_face_pose_landmarks.csv
[27/43] R595WP_VX_driver_video_face_pose_landmarks.csv
[28/43] R8YB77_VX_driver_video_face_pose_landmarks.csv
  ERROR: Driver/ET mapping is not usable
[29/43] RYE8J9_VX_driver_video_face_pose_landmarks.csv
[30/43] RZKLE8_VX_driver_video_face_pose_landmarks.csv
[31/43] S99GF9_VX_driver_video_face_pose_landmarks.csv
[32/43] SHUPW7_VX_driver_video_face_pose_landmarks.csv
[33/43] SPKHNL_VX_driver_video_face_pose_landmarks.csv
[34/43] TXRE5B_VX_driver_video_face_pose_landmarks.csv
[35/43] U83GH3_VX_driver_video_face_pose_landmarks.csv
[36/43] UY6WA8_VX_driver_video_face_pose_landmarks.csv
[37/43] V3SLBM_VX_driver_video_face_pose_landmarks.csv
  ERROR: Driver/ET mapping is not usable
[38/43] VUT5TP_VX_driver_video_face_pose_landmarks.csv
[39/43] W3MTYZ_VX_driver_video_face_pose_landmarks.csv
  ERROR: ET/LSL mapping is not usable
[40/43] XJF6R9_VX_driver_video_face_pose_landmarks.csv
[41/43] YHYKDQ_VX_driver_video_face_pose_landmarks.csv
[42/43] Z8HDMS_VX_driver_video_face_pose_landmarks.csv
[43/43] ZQTXLD_VX_driver_video_face_pose_landmarks.csv

,project,participant,visit,segment_id,video_path,landmark_csv_path,output_path,status,frames,driver_et_mapping_status,et_lsl_mapping_status,et_raw_time_count,lsl_time_count,error
0,ImBrAid,A7G5SM,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\A...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13653.0,affine,content_affine,13653.0,13653.0,
1,ImBrAid,ABVLGQ,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\A...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13630.0,affine,content_affine,13630.0,13630.0,
2,ImBrAid,B9NYQ8,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\B...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13529.0,affine,content_affine,13529.0,13529.0,
3,ImBrAid,CRVWF9,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\C...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13437.0,affine,content_affine,13437.0,13437.0,
4,ImBrAid,CRYSEP,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\C...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13665.0,affine,content_affine,13665.0,13665.0,
5,ImBrAid,CU6DM4,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\C...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,14025.0,affine,content_affine,14025.0,14025.0,
6,ImBrAid,DUJL2L,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\D...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13895.0,affine,content_affine,13895.0,13895.0,
7,ImBrAid,E4MKXT,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\E...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13729.0,affine,content_affine,13729.0,13729.0,
8,ImBrAid,EASFXM,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\E...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,14143.0,affine,content_affine,14143.0,14143.0,
9,ImBrAid,FEDZAG,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\F...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13363.0,offset_only,content_affine,13363.0,13363.0,
10,ImBrAid,FGJK2B,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\F...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13529.0,affine,content_affine,13529.0,13529.0,
11,ImBrAid,FLZWD8,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\F...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13419.0,affine,content_affine,13419.0,13419.0,
12,ImBrAid,G93LYM,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\G...,E:\test\DatasetForPublish\preprocessed_data\Dr...,error,NaN,offset_only,unavailable,NaN,NaN,ValueError('ET/LSL mapping is not usable')
13,ImBrAid,GLRNU9,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\G...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,11881.0,offset_only,content_affine,11881.0,11881.0,
14,ImBrAid,HH5RBX,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\H...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13451.0,offset_only,content_affine,13451.0,13451.0,
15,ImBrAid,HKJPM3,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\H...,E:\test\DatasetForPublish\preprocessed_data\Dr...,error,NaN,unavailable,unavailable,NaN,NaN,ValueError('Driver/ET mapping is not usable')
16,ImBrAid,HNWSPB,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\H...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13641.0,review_affine,content_affine,13641.0,13641.0,
17,ImBrAid,JVC62S,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\J...,E:\test\DatasetForPublish\preprocessed_data\Dr...,error,NaN,invalid_affine,unavailable,NaN,NaN,ValueError('Driver/ET mapping is not usable')
18,ImBrAid,LGJEFY,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\L...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13552.0,affine,content_affine,13552.0,13552.0,
19,ImBrAid,LKK2WT,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\L...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13686.0,affine,content_affine,13686.0,13686.0,
20,ImBrAid,MUHKQF,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\M...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13802.0,offset_only,content_affine,13802.0,13802.0,
21,ImBrAid,N37VFK,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\N...,E:\test\DatasetForPublish\preprocessed_data\Dr...,error,NaN,affine,unavailable,NaN,NaN,ValueError('ET/LSL mapping is not usable')
22,ImBrAid,N7C4A6,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\N...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13649.0,affine,content_affine,13649.0,13649.0,
23,ImBrAid,NJN65T,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\N...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13785.0,affine,content_affine,13785.0,13785.0,
24,ImBrAid,PJ52F4,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\P...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13567.0,affine,content_affine,13567.0,13567.0,
25,ImBrAid,Q5ZPCB,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\Q...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13526.0,affine,content_affine,13526.0,13526.0,
26,ImBrAid,R595WP,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\R...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13541.0,affine,content_affine,13541.0,13541.0,
27,ImBrAid,R8YB77,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\R...,E:\test\DatasetForPublish\preprocessed_data\Dr...,error,NaN,invalid_affine,content_affine,NaN,NaN,ValueError('Driver/ET mapping is not usable')
28,ImBrAid,RYE8J9,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\R...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13511.0,affine,content_affine,13511.0,13511.0,
29,ImBrAid,RZKLE8,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\R...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13797.0,offset_only,content_affine,13797.0,13797.0,
30,ImBrAid,S99GF9,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\S...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13717.0,offset_only,content_affine,13717.0,13717.0,
31,ImBrAid,SHUPW7,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\S...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13973.0,affine,content_affine,13973.0,13973.0,
32,ImBrAid,SPKHNL,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\S...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13161.0,affine,content_affine,13161.0,13161.0,
33,ImBrAid,TXRE5B,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\T...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13602.0,affine,content_affine,13602.0,13602.0,
34,ImBrAid,U83GH3,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\U...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13293.0,affine,content_affine,13293.0,13293.0,
35,ImBrAid,UY6WA8,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\U...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13380.0,affine,content_affine,13380.0,13380.0,
36,ImBrAid,V3SLBM,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\V...,E:\test\DatasetForPublish\preprocessed_data\Dr...,error,NaN,unavailable,unavailable,NaN,NaN,ValueError('Driver/ET mapping is not usable')
37,ImBrAid,VUT5TP,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\V...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13712.0,affine,content_affine,13712.0,13712.0,
38,ImBrAid,W3MTYZ,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\W...,E:\test\DatasetForPublish\preprocessed_data\Dr...,error,NaN,review_affine,unavailable,NaN,NaN,ValueError('ET/LSL mapping is not usable')
39,ImBrAid,XJF6R9,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\X...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,14271.0,affine,content_affine,14271.0,14271.0,
40,ImBrAid,YHYKDQ,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\Y...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13565.0,affine,content_affine,13565.0,13565.0,
41,ImBrAid,Z8HDMS,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\Z...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,13252.0,affine,content_affine,13252.0,13252.0,
42,ImBrAid,ZQTXLD,VX,main,,E:\test\processed\DriverVideo_Face_Landmarks\Z...,E:\test\DatasetForPublish\preprocessed_data\Dr...,written_driver_et_lsl,14568.0,affine,content_affine,14568.0,14568.0,

## IDUN publication files

In [4]:
idun_summary = None
if IDUN_LSL_CSV.is_file():
    idun_mappings = pd.read_csv(IDUN_LSL_CSV, dtype=str, keep_default_na=False)
    idun_summary, idun_issues = idun_export.export_synchronized_idun_data(
        idun_mappings, output_dir=IDUN_OUTPUT_DIR,
        et_lsl_alignment_csv=ET_LSL_CSV if ET_LSL_CSV.is_file() else None,
        overwrite=OVERWRITE,
    )
    idun_export.save_idun_export_summary(idun_summary, IDUN_SUMMARY_CSV)
    idun_export.save_idun_export_issues(idun_issues, IDUN_ISSUES_CSV)
    display(idun_summary)
    display(idun_issues)
else:
    print('IDUN skipped: its mapping file is absent.')

,project,pid,visit,export_status,idun_mapping_status,idun_quality_grade,synchronized_csv_path,source_raw_csv_path,sample_count,lsl_timestamp_count,lsl_supported_sample_count,lsl_extrapolated_sample_count,lsl_supported_fraction,et_raw_mapping_status,et_raw_quality_grade,et_raw_timestamp_count,et_raw_supported_sample_count,et_raw_extrapolated_sample_count,et_raw_supported_fraction,warnings
0,ImBrAid,A7G5SM,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
1,ImBrAid,ABVLGQ,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\ABVLGQ\IDUN\ABVLGQ_VX_eeg...,739720.0,739720.0,675000.0,64720.0,0.912507,content_affine,A,739720.0,675000.0,64720.0,0.912507,
2,ImBrAid,B9NYQ8,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
3,ImBrAid,CRVWF9,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\CRVWF9\IDUN\CRVWF9_VX_eeg...,715060.0,715060.0,637500.0,77560.0,0.891534,content_affine,A,715060.0,637500.0,77560.0,0.891534,
4,ImBrAid,CRYSEP,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\CRYSEP\IDUN\CRYSEP_VX_eeg...,326480.0,326480.0,262501.0,63979.0,0.804034,content_affine,A,326480.0,262501.0,63979.0,0.804034,
5,ImBrAid,CU6DM4,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\CU6DM4\IDUN\CU6DM4_VX_eeg...,775700.0,775700.0,675001.0,100699.0,0.870183,content_affine,A,775700.0,675001.0,100699.0,0.870183,
6,ImBrAid,DUJL2L,VX,written,affine_review,B,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\DUJL2L\IDUN\DUJL2L_VX_eeg...,727120.0,727120.0,675000.0,52120.0,0.928320,content_affine,A,727120.0,675000.0,52120.0,0.928320,
7,ImBrAid,E4MKXT,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\E4MKXT\IDUN\E4MKXT_VX_eeg...,721500.0,721500.0,637500.0,84000.0,0.883576,content_affine,A,721500.0,637500.0,84000.0,0.883576,
8,ImBrAid,EASFXM,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\EASFXM\IDUN\EASFXM_VX_eeg...,728180.0,728180.0,675000.0,53180.0,0.926969,content_affine,A,728180.0,675000.0,53180.0,0.926969,
9,ImBrAid,FEDZAG,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\FEDZAG\IDUN\FEDZAG_VX_eeg...,727060.0,727060.0,637501.0,89559.0,0.876820,content_affine,A,727060.0,637501.0,89559.0,0.876820,
10,ImBrAid,FGJK2B,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
11,ImBrAid,FLZWD8,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\FLZWD8\IDUN\FLZWD8_VX_eeg...,741540.0,741540.0,637501.0,104039.0,0.859699,content_affine,A,741540.0,637501.0,104039.0,0.859699,
12,ImBrAid,G93LYM,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\G93LYM\IDUN\G93LYM_VX_eeg...,694020.0,694020.0,637501.0,56519.0,0.918563,unavailable,D,0.0,0.0,0.0,0.000000,ET raw/LSL mapping was not used; et_raw_timest...
13,ImBrAid,GLRNU9,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\GLRNU9\IDUN\GLRNU9_VX_eeg...,606540.0,606540.0,525001.0,81539.0,0.865567,content_affine,A,606540.0,525001.0,81539.0,0.865567,
14,ImBrAid,HH5RBX,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\HH5RBX\IDUN\HH5RBX_VX_eeg...,706740.0,706740.0,628960.0,77780.0,0.889945,content_affine,A,706740.0,615208.0,91532.0,0.870487,
15,ImBrAid,HKJPM3,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
16,ImBrAid,HNWSPB,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
17,ImBrAid,JVC62S,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
18,ImBrAid,LGJEFY,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\LGJEFY\IDUN\LGJEFY_VX_eeg...,699180.0,699180.0,675001.0,24179.0,0.965418,content_affine,A,699180.0,675001.0,24179.0,0.965418,
19,ImBrAid,LKK2WT,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\LKK2WT\IDUN\LKK2WT_VX_eeg...,701680.0,701680.0,675001.0,26679.0,0.961978,content_affine,B,701680.0,675001.0,26679.0,0.961978,
20,ImBrAid,MUHKQF,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\MUHKQF\IDUN\MUHKQF_VX_eeg...,702220.0,702220.0,675001.0,27219.0,0.961239,content_affine,A,702220.0,392883.0,309337.0,0.559487,
21,ImBrAid,N37VFK,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
22,ImBrAid,N7C4A6,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
23,ImBrAid,NJN65T,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
24,ImBrAid,PJ52F4,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\PJ52F4\IDUN\PJ52F4_VX_eeg...,728720.0,728720.0,675001.0,53719.0,0.926283,content_affine,A,728720.0,675001.0,53719.0,0.926283,
25,ImBrAid,Q5ZPCB,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
26,ImBrAid,R595WP,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\R595WP\IDUN\R595WP_VX_eeg...,684720.0,684720.0,675001.0,9719.0,0.985806,content_affine,A,684720.0,675001.0,9719.0,0.985806,
27,ImBrAid,R8YB77,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
28,ImBrAid,RYE8J9,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\RYE8J9\IDUN\RYE8J9_VX_eeg...,681920.0,681920.0,637500.0,44420.0,0.934860,content_affine,A,681920.0,637500.0,44420.0,0.934860,
29,ImBrAid,RZKLE8,VX,written,affine_review,B,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\RZKLE8\IDUN\RZKLE8_VX_eeg...,732800.0,732800.0,675000.0,57800.0,0.921124,content_affine,A,732800.0,478401.0,254399.0,0.652840,
30,ImBrAid,S99GF9,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
31,ImBrAid,SHUPW7,VX,skipped_unavailable,unavailable,D,NaN,E:\test\time_shifted\SHUPW7\IDUN\SHUPW7_VX_eeg...,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
32,ImBrAid,SPKHNL,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\SPKHNL\IDUN\SPKHNL_VX_eeg...,760060.0,760060.0,562500.0,197560.0,0.740073,content_affine,A,760060.0,562500.0,197560.0,0.740073,
33,ImBrAid,TXRE5B,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\TXRE5B\IDUN\TXRE5B_VX_eeg...,695920.0,695920.0,637500.0,58420.0,0.916054,content_affine,A,695920.0,636179.0,59741.0,0.914155,
34,ImBrAid,U83GH3,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\U83GH3\IDUN\U83GH3_VX_eeg...,679000.0,679000.0,637481.0,41519.0,0.938853,content_affine,A,679000.0,637481.0,41519.0,0.938853,
35,ImBrAid,UY6WA8,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\UY6WA8\IDUN\UY6WA8_VX_eeg...,685160.0,685160.0,637501.0,47659.0,0.930441,content_affine,A,685160.0,637501.0,47659.0,0.930441,
36,ImBrAid,V3SLBM,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
37,ImBrAid,VUT5TP,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\VUT5TP\IDUN\VUT5TP_VX_eeg...,746080.0,746080.0,675000.0,71080.0,0.904729,content_affine,A,746080.0,675000.0,71080.0,0.904729,
38,ImBrAid,W3MTYZ,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
39,ImBrAid,XJF6R9,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
40,ImBrAid,YHYKDQ,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\YHYKDQ\IDUN\YHYKDQ_VX_eeg...,694180.0,694180.0,675001.0,19179.0,0.972372,content_affine,A,694180.0,675001.0,19179.0,0.972372,
41,ImBrAid,Z8HDMS,VX,skipped_unavailable,unavailable,D,NaN,,NaN,NaN,NaN,NaN,NaN,not_requested,NaN,NaN,NaN,NaN,NaN,IDUN/LSL mapping is unavailable: unavailable
42,ImBrAid,ZQTXLD,VX,written,affine,A,E:\test\DatasetForPublish\preprocessed_data\ID...,E:\test\time_shifted\ZQTXLD\IDUN\ZQTXLD_VX_eeg...,689360.0,689360.0,675001.0,14359.0,0.979171,content_affine,A,689360.0,675001.0,14359.0,0.979171,

,project,pid,visit,severity,issue,detail
0,ImBrAid,A7G5SM,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
1,ImBrAid,B9NYQ8,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
2,ImBrAid,FGJK2B,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
3,ImBrAid,G93LYM,VX,warning,synchronized_timestamp_warning,ET raw/LSL mapping was not used; et_raw_timest...
4,ImBrAid,HKJPM3,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
5,ImBrAid,HNWSPB,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
6,ImBrAid,JVC62S,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
7,ImBrAid,N37VFK,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
8,ImBrAid,N7C4A6,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
9,ImBrAid,NJN65T,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
10,ImBrAid,Q5ZPCB,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
11,ImBrAid,R8YB77,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
12,ImBrAid,S99GF9,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
13,ImBrAid,SHUPW7,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
14,ImBrAid,V3SLBM,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
15,ImBrAid,W3MTYZ,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
16,ImBrAid,XJF6R9,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable
17,ImBrAid,Z8HDMS,VX,warning,idun_mapping_unavailable,IDUN/LSL mapping is unavailable: unavailable

## Finish

In [5]:
print('Finished all available modality exports.')

Finished all available modality exports.